# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule HookSniffAPI.Model.Notification do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :title,
    :body,
    :is_read,
    :link,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :title => String.t | nil,
    :body => String.t | nil,
    :is_read => boolean() | nil,
    :link => String.t | nil,
    :created_at => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

