apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/name: hooksniff
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hooksniff
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dashboard
  labels:
    app.kubernetes.io/name: hooksniff
    app.kubernetes.io/component: dashboard
spec:
  type: {{ .Values.service.dashboard.type }}
  ports:
    - port: {{ .Values.service.dashboard.port }}
      targetPort: {{ .Values.dashboard.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hooksniff
    app.kubernetes.io/component: dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app.kubernetes.io/name: hooksniff
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: hooksniff
    app.kubernetes.io/component: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app.kubernetes.io/name: hooksniff
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: hooksniff
    app.kubernetes.io/component: redis
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  jwt-secret: {{ .Values.env.JWT_SECRET | b64enc | quote }}
  hmac-secret: {{ .Values.env.HMAC_SECRET | b64enc | quote }}
