/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hooksniff.apis.AdminApi
import hooksniff.models.AdminAlertRule
import hooksniff.models.AdminAlertsIdDelete200Response
import hooksniff.models.AdminAuditLogResponse
import hooksniff.models.AdminCreateAlertRequest
import hooksniff.models.AdminFeatureFlagsGet200Response
import hooksniff.models.AdminFeatureFlagsIdPutRequest
import hooksniff.models.AdminFeatureFlagsPostRequest
import hooksniff.models.AdminSdkUpdatePostRequest
import hooksniff.models.AdminSettingsPut200Response
import hooksniff.models.AdminTestWebhookRequest
import hooksniff.models.AdminTestWebhookResponse
import hooksniff.models.AdminUpdateAlertRequest
import hooksniff.models.AdminUsersIdGet200Response
import hooksniff.models.AdminUsersIdPlanPutRequest
import hooksniff.models.AdminUsersIdStatusPutRequest
import hooksniff.models.ChurnResponse
import hooksniff.models.DeployInfo
import hooksniff.models.FeatureFlag
import hooksniff.models.PaginatedUsers
import hooksniff.models.PlatformSettings
import hooksniff.models.ReplayDeliveryResponse
import hooksniff.models.RevenueResponse
import hooksniff.models.SystemStats
import hooksniff.models.UserAnalytics

class AdminApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AdminApi
        //val apiInstance = AdminApi()

        // to test adminAlertsGet
        should("test adminAlertsGet") {
            // uncomment below to test adminAlertsGet
            //val result : kotlin.collections.List<AdminAlertRule> = apiInstance.adminAlertsGet()
            //result shouldBe ("TODO")
        }

        // to test adminAlertsIdDelete
        should("test adminAlertsIdDelete") {
            // uncomment below to test adminAlertsIdDelete
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : AdminAlertsIdDelete200Response = apiInstance.adminAlertsIdDelete(id)
            //result shouldBe ("TODO")
        }

        // to test adminAlertsIdPut
        should("test adminAlertsIdPut") {
            // uncomment below to test adminAlertsIdPut
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val adminUpdateAlertRequest : AdminUpdateAlertRequest =  // AdminUpdateAlertRequest | 
            //val result : AdminAlertRule = apiInstance.adminAlertsIdPut(id, adminUpdateAlertRequest)
            //result shouldBe ("TODO")
        }

        // to test adminAlertsPost
        should("test adminAlertsPost") {
            // uncomment below to test adminAlertsPost
            //val adminCreateAlertRequest : AdminCreateAlertRequest =  // AdminCreateAlertRequest | 
            //val result : AdminAlertRule = apiInstance.adminAlertsPost(adminCreateAlertRequest)
            //result shouldBe ("TODO")
        }

        // to test adminAuditLogsGet
        should("test adminAuditLogsGet") {
            // uncomment below to test adminAuditLogsGet
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val perPage : kotlin.Int = 56 // kotlin.Int | 
            //val action : kotlin.String = action_example // kotlin.String | 
            //val adminId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : AdminAuditLogResponse = apiInstance.adminAuditLogsGet(page, perPage, action, adminId)
            //result shouldBe ("TODO")
        }

        // to test adminChurnGet
        should("test adminChurnGet") {
            // uncomment below to test adminChurnGet
            //val result : ChurnResponse = apiInstance.adminChurnGet()
            //result shouldBe ("TODO")
        }

        // to test adminDeliveriesIdReplayPost
        should("test adminDeliveriesIdReplayPost") {
            // uncomment below to test adminDeliveriesIdReplayPost
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | Original delivery ID to replay
            //val result : ReplayDeliveryResponse = apiInstance.adminDeliveriesIdReplayPost(id)
            //result shouldBe ("TODO")
        }

        // to test adminDeployInfoGet
        should("test adminDeployInfoGet") {
            // uncomment below to test adminDeployInfoGet
            //val result : DeployInfo = apiInstance.adminDeployInfoGet()
            //result shouldBe ("TODO")
        }

        // to test adminFeatureFlagsGet
        should("test adminFeatureFlagsGet") {
            // uncomment below to test adminFeatureFlagsGet
            //val result : AdminFeatureFlagsGet200Response = apiInstance.adminFeatureFlagsGet()
            //result shouldBe ("TODO")
        }

        // to test adminFeatureFlagsIdDelete
        should("test adminFeatureFlagsIdDelete") {
            // uncomment below to test adminFeatureFlagsIdDelete
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.adminFeatureFlagsIdDelete(id)
        }

        // to test adminFeatureFlagsIdPut
        should("test adminFeatureFlagsIdPut") {
            // uncomment below to test adminFeatureFlagsIdPut
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val adminFeatureFlagsIdPutRequest : AdminFeatureFlagsIdPutRequest =  // AdminFeatureFlagsIdPutRequest | 
            //val result : FeatureFlag = apiInstance.adminFeatureFlagsIdPut(id, adminFeatureFlagsIdPutRequest)
            //result shouldBe ("TODO")
        }

        // to test adminFeatureFlagsPost
        should("test adminFeatureFlagsPost") {
            // uncomment below to test adminFeatureFlagsPost
            //val adminFeatureFlagsPostRequest : AdminFeatureFlagsPostRequest =  // AdminFeatureFlagsPostRequest | 
            //val result : FeatureFlag = apiInstance.adminFeatureFlagsPost(adminFeatureFlagsPostRequest)
            //result shouldBe ("TODO")
        }

        // to test adminRevenueExportGet
        should("test adminRevenueExportGet") {
            // uncomment below to test adminRevenueExportGet
            //val format : kotlin.String = format_example // kotlin.String | 
            //val months : kotlin.Int = 56 // kotlin.Int | Number of months to include
            //val result : kotlin.String = apiInstance.adminRevenueExportGet(format, months)
            //result shouldBe ("TODO")
        }

        // to test adminRevenueGet
        should("test adminRevenueGet") {
            // uncomment below to test adminRevenueGet
            //val result : RevenueResponse = apiInstance.adminRevenueGet()
            //result shouldBe ("TODO")
        }

        // to test adminSdkUpdatePost
        should("test adminSdkUpdatePost") {
            // uncomment below to test adminSdkUpdatePost
            //val adminSdkUpdatePostRequest : AdminSdkUpdatePostRequest =  // AdminSdkUpdatePostRequest | 
            //apiInstance.adminSdkUpdatePost(adminSdkUpdatePostRequest)
        }

        // to test adminSettingsGet
        should("test adminSettingsGet") {
            // uncomment below to test adminSettingsGet
            //val result : PlatformSettings = apiInstance.adminSettingsGet()
            //result shouldBe ("TODO")
        }

        // to test adminSettingsPut
        should("test adminSettingsPut") {
            // uncomment below to test adminSettingsPut
            //val platformSettings : PlatformSettings =  // PlatformSettings | 
            //val result : AdminSettingsPut200Response = apiInstance.adminSettingsPut(platformSettings)
            //result shouldBe ("TODO")
        }

        // to test adminStatsGet
        should("test adminStatsGet") {
            // uncomment below to test adminStatsGet
            //val result : SystemStats = apiInstance.adminStatsGet()
            //result shouldBe ("TODO")
        }

        // to test adminTestWebhookPost
        should("test adminTestWebhookPost") {
            // uncomment below to test adminTestWebhookPost
            //val adminTestWebhookRequest : AdminTestWebhookRequest =  // AdminTestWebhookRequest | 
            //val result : AdminTestWebhookResponse = apiInstance.adminTestWebhookPost(adminTestWebhookRequest)
            //result shouldBe ("TODO")
        }

        // to test adminUsersExportGet
        should("test adminUsersExportGet") {
            // uncomment below to test adminUsersExportGet
            //val format : kotlin.String = format_example // kotlin.String | 
            //val plan : kotlin.String = plan_example // kotlin.String | Filter by plan
            //val status : kotlin.String = status_example // kotlin.String | Filter by status
            //val result : kotlin.String = apiInstance.adminUsersExportGet(format, plan, status)
            //result shouldBe ("TODO")
        }

        // to test adminUsersGet
        should("test adminUsersGet") {
            // uncomment below to test adminUsersGet
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val perPage : kotlin.Int = 56 // kotlin.Int | 
            //val search : kotlin.String = search_example // kotlin.String | Search by email or name (ILIKE)
            //val plan : kotlin.String = plan_example // kotlin.String | Filter by plan
            //val status : kotlin.String = status_example // kotlin.String | Filter by status
            //val createdAfter : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | Filter users created after this date (ISO 8601)
            //val createdBefore : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | Filter users created before this date (ISO 8601)
            //val result : PaginatedUsers = apiInstance.adminUsersGet(page, perPage, search, plan, status, createdAfter, createdBefore)
            //result shouldBe ("TODO")
        }

        // to test adminUsersIdAnalyticsGet
        should("test adminUsersIdAnalyticsGet") {
            // uncomment below to test adminUsersIdAnalyticsGet
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val days : kotlin.Int = 56 // kotlin.Int | Number of days to analyze
            //val result : UserAnalytics = apiInstance.adminUsersIdAnalyticsGet(id, days)
            //result shouldBe ("TODO")
        }

        // to test adminUsersIdGet
        should("test adminUsersIdGet") {
            // uncomment below to test adminUsersIdGet
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : AdminUsersIdGet200Response = apiInstance.adminUsersIdGet(id)
            //result shouldBe ("TODO")
        }

        // to test adminUsersIdPlanPut
        should("test adminUsersIdPlanPut") {
            // uncomment below to test adminUsersIdPlanPut
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val adminUsersIdPlanPutRequest : AdminUsersIdPlanPutRequest =  // AdminUsersIdPlanPutRequest | 
            //apiInstance.adminUsersIdPlanPut(id, adminUsersIdPlanPutRequest)
        }

        // to test adminUsersIdStatusPut
        should("test adminUsersIdStatusPut") {
            // uncomment below to test adminUsersIdStatusPut
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val adminUsersIdStatusPutRequest : AdminUsersIdStatusPutRequest =  // AdminUsersIdStatusPutRequest | 
            //apiInstance.adminUsersIdStatusPut(id, adminUsersIdStatusPutRequest)
        }

    }
}
