/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hooksniff.apis.DevicesApi
import hooksniff.models.DeviceTokenResponse
import hooksniff.models.RegisterDeviceRequest

class DevicesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DevicesApi
        //val apiInstance = DevicesApi()

        // to test devicesGet
        should("test devicesGet") {
            // uncomment below to test devicesGet
            //val result : kotlin.collections.List<DeviceTokenResponse> = apiInstance.devicesGet()
            //result shouldBe ("TODO")
        }

        // to test devicesPost
        should("test devicesPost") {
            // uncomment below to test devicesPost
            //val registerDeviceRequest : RegisterDeviceRequest =  // RegisterDeviceRequest | 
            //val result : DeviceTokenResponse = apiInstance.devicesPost(registerDeviceRequest)
            //result shouldBe ("TODO")
        }

        // to test devicesTokenDelete
        should("test devicesTokenDelete") {
            // uncomment below to test devicesTokenDelete
            //val token : kotlin.String = token_example // kotlin.String | 
            //apiInstance.devicesTokenDelete(token)
        }

    }
}
