/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hooksniff.apis.SimulatorApi
import hooksniff.models.SimulatorPostRequest

class SimulatorApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SimulatorApi
        //val apiInstance = SimulatorApi()

        // to test simulatorPost
        should("test simulatorPost") {
            // uncomment below to test simulatorPost
            //val simulatorPostRequest : SimulatorPostRequest =  // SimulatorPostRequest | 
            //apiInstance.simulatorPost(simulatorPostRequest)
        }

    }
}
