/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param totalDeliveries 
 * @param successRate 
 * @param endpointsCount 
 */


data class AdminUsersIdGet200ResponseUsageStats (

    @Json(name = "total_deliveries")
    val totalDeliveries: kotlin.Int? = null,

    @Json(name = "success_rate")
    val successRate: kotlin.Double? = null,

    @Json(name = "endpoints_count")
    val endpointsCount: kotlin.Int? = null

) {


}

