/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param email 
 * @param plan 
 * @param webhookLimit 
 * @param webhookCount 
 * @param isAdmin 
 * @param createdAt 
 * @param name 
 * @param apiKey Only returned on registration
 */


data class CustomerResponse (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "plan")
    val plan: CustomerResponse.Plan,

    @Json(name = "webhook_limit")
    val webhookLimit: kotlin.Int,

    @Json(name = "webhook_count")
    val webhookCount: kotlin.Int,

    @Json(name = "is_admin")
    val isAdmin: kotlin.Boolean,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Only returned on registration */
    @Json(name = "api_key")
    val apiKey: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: free,pro,business
     */
    @JsonClass(generateAdapter = false)
    enum class Plan(val value: kotlin.String) {
        @Json(name = "free") free("free"),
        @Json(name = "pro") pro("pro"),
        @Json(name = "business") business("business");
    }

}

