/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models

import hooksniff.models.Delivery

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param deliveries 
 * @param total 
 * @param page 
 * @param perPage 
 */


data class DeliveryListResponse (

    @Json(name = "deliveries")
    val deliveries: kotlin.collections.List<Delivery>,

    @Json(name = "total")
    val total: kotlin.Int,

    @Json(name = "page")
    val page: kotlin.Int,

    @Json(name = "per_page")
    val perPage: kotlin.Int

) {


}

