/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models

import hooksniff.models.DeviceTokenResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Paginated list of registered devices
 *
 * @param `data` 
 */


data class DeviceListResponse (

    @Json(name = "data")
    val `data`: kotlin.collections.List<DeviceTokenResponse>

) {


}

