/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Latency percentile breakdown for deliveries
 *
 * @param p50 50th percentile (median) latency in ms
 * @param p90 90th percentile latency in ms
 * @param p95 95th percentile latency in ms
 * @param p99 99th percentile latency in ms
 * @param period Time range of the data
 */


data class LatencyResponse (

    /* 50th percentile (median) latency in ms */
    @Json(name = "p50")
    val p50: kotlin.Float,

    /* 90th percentile latency in ms */
    @Json(name = "p90")
    val p90: kotlin.Float,

    /* 95th percentile latency in ms */
    @Json(name = "p95")
    val p95: kotlin.Float,

    /* 99th percentile latency in ms */
    @Json(name = "p99")
    val p99: kotlin.Float,

    /* Time range of the data */
    @Json(name = "period")
    val period: LatencyResponse.Period

) {

    /**
     * Time range of the data
     *
     * Values: _24h,_7d,_30d
     */
    @JsonClass(generateAdapter = false)
    enum class Period(val value: kotlin.String) {
        @Json(name = "24h") _24h("24h"),
        @Json(name = "7d") _7d("7d"),
        @Json(name = "30d") _30d("30d");
    }

}

