/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Temporary session token for the customer portal
 *
 * @param token 
 * @param expiresAt 
 * @param url Full URL to the portal with session token
 */


data class PortalSession (

    @Json(name = "token")
    val token: kotlin.String,

    @Json(name = "expires_at")
    val expiresAt: java.time.OffsetDateTime,

    /* Full URL to the portal with session token */
    @Json(name = "url")
    val url: java.net.URI

) {


}

