/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Result of a simulated webhook delivery
 *
 * @param deliveryId 
 * @param status 
 * @param latencyMs Response time from the endpoint
 */


data class SimulatorResponse (

    @Json(name = "delivery_id")
    val deliveryId: java.util.UUID,

    @Json(name = "status")
    val status: SimulatorResponse.Status,

    /* Response time from the endpoint */
    @Json(name = "latency_ms")
    val latencyMs: kotlin.Int

) {

    /**
     * 
     *
     * Values: delivered,failed,pending
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "delivered") delivered("delivered"),
        @Json(name = "failed") failed("failed"),
        @Json(name = "pending") pending("pending");
    }

}

