/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param endpointId 
 * @param name 
 * @param ruleType 
 * @param isActive 
 * @param createdAt 
 * @param config 
 */


data class TransformRule (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "endpoint_id")
    val endpointId: java.util.UUID,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "rule_type")
    val ruleType: kotlin.String,

    @Json(name = "is_active")
    val isActive: kotlin.Boolean,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "config")
    val config: kotlin.Any? = null

) {


}

