/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param routingStrategy 
 * @param fallbackUrl 
 */


data class UpdateRoutingRequest (

    @Json(name = "routing_strategy")
    val routingStrategy: UpdateRoutingRequest.RoutingStrategy,

    @Json(name = "fallback_url")
    val fallbackUrl: java.net.URI

) {

    /**
     * 
     *
     * Values: roundMinusRobin,latency,failover
     */
    @JsonClass(generateAdapter = false)
    enum class RoutingStrategy(val value: kotlin.String) {
        @Json(name = "round-robin") roundMinusRobin("round-robin"),
        @Json(name = "latency") latency("latency"),
        @Json(name = "failover") failover("failover");
    }

}

