/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Update an existing routing rule (all fields optional)
 *
 * @param name 
 * @param conditions 
 * @param transform 
 */


data class UpdateRoutingRuleRequest (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "conditions")
    val conditions: kotlin.Any? = null,

    @Json(name = "transform")
    val transform: kotlin.Any? = null

) {


}

