/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hooksniff.models.AdminUsersIdGet200ResponseRecentDeliveriesInner

class AdminUsersIdGet200ResponseRecentDeliveriesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AdminUsersIdGet200ResponseRecentDeliveriesInner
        //val modelInstance = AdminUsersIdGet200ResponseRecentDeliveriesInner()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `endpointId`
        should("test endpointId") {
            // uncomment below to test the property
            //modelInstance.endpointId shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `eventType`
        should("test eventType") {
            // uncomment below to test the property
            //modelInstance.eventType shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `attemptCount`
        should("test attemptCount") {
            // uncomment below to test the property
            //modelInstance.attemptCount shouldBe ("TODO")
        }

    }
}
