/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hooksniff.models.AdminSdkUpdatePostRequest

class AdminSdkUpdatePostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AdminSdkUpdatePostRequest
        //val modelInstance = AdminSdkUpdatePostRequest()

        // to test the property `version`
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
