/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hooksniff.models.AdminUsersIdGet200Response
import hooksniff.models.AdminUsersIdGet200ResponseEndpointsInner
import hooksniff.models.AdminUsersIdGet200ResponseRecentDeliveriesInner
import hooksniff.models.AdminUsersIdGet200ResponseUsageStats
import hooksniff.models.UserSummary

class AdminUsersIdGet200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AdminUsersIdGet200Response
        //val modelInstance = AdminUsersIdGet200Response()

        // to test the property `user`
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `endpoints`
        should("test endpoints") {
            // uncomment below to test the property
            //modelInstance.endpoints shouldBe ("TODO")
        }

        // to test the property `recentDeliveries`
        should("test recentDeliveries") {
            // uncomment below to test the property
            //modelInstance.recentDeliveries shouldBe ("TODO")
        }

        // to test the property `usageStats`
        should("test usageStats") {
            // uncomment below to test the property
            //modelInstance.usageStats shouldBe ("TODO")
        }

    }
}
