/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hooksniff.models.AdminRevenueEntry

class AdminRevenueEntryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AdminRevenueEntry
        //val modelInstance = AdminRevenueEntry()

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `mrr` - Monthly recurring revenue in dollars
        should("test mrr") {
            // uncomment below to test the property
            //modelInstance.mrr shouldBe ("TODO")
        }

        // to test the property `newSubscriptions`
        should("test newSubscriptions") {
            // uncomment below to test the property
            //modelInstance.newSubscriptions shouldBe ("TODO")
        }

        // to test the property `churns`
        should("test churns") {
            // uncomment below to test the property
            //modelInstance.churns shouldBe ("TODO")
        }

    }
}
