/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hooksniff.models.ApiKeyInfo

class ApiKeyInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApiKeyInfo
        //val modelInstance = ApiKeyInfo()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `prefix` - Masked key prefix (e.g. \"hs_abc1...\")
        should("test prefix") {
            // uncomment below to test the property
            //modelInstance.prefix shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `isActive`
        should("test isActive") {
            // uncomment below to test the property
            //modelInstance.isActive shouldBe ("TODO")
        }

        // to test the property `lastUsedAt`
        should("test lastUsedAt") {
            // uncomment below to test the property
            //modelInstance.lastUsedAt shouldBe ("TODO")
        }

    }
}
