/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hooksniff.models.DeviceTokenResponse

class DeviceTokenResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeviceTokenResponse
        //val modelInstance = DeviceTokenResponse()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `token`
        should("test token") {
            // uncomment below to test the property
            //modelInstance.token shouldBe ("TODO")
        }

        // to test the property `platform`
        should("test platform") {
            // uncomment below to test the property
            //modelInstance.platform shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

    }
}
