/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hooksniff.models.LatencyTrendResponseBucketsInner

class LatencyTrendResponseBucketsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LatencyTrendResponseBucketsInner
        //val modelInstance = LatencyTrendResponseBucketsInner()

        // to test the property `timestamp`
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `avgMs`
        should("test avgMs") {
            // uncomment below to test the property
            //modelInstance.avgMs shouldBe ("TODO")
        }

        // to test the property `p95Ms`
        should("test p95Ms") {
            // uncomment below to test the property
            //modelInstance.p95Ms shouldBe ("TODO")
        }

    }
}
