/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hooksniff.models.PlaygroundGet200Response

class PlaygroundGet200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlaygroundGet200Response
        //val modelInstance = PlaygroundGet200Response()

        // to test the property `endpoints`
        should("test endpoints") {
            // uncomment below to test the property
            //modelInstance.endpoints shouldBe ("TODO")
        }

        // to test the property `samplePayloads`
        should("test samplePayloads") {
            // uncomment below to test the property
            //modelInstance.samplePayloads shouldBe ("TODO")
        }

    }
}
