/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hooksniff.models.SimulatorResponse

class SimulatorResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SimulatorResponse
        //val modelInstance = SimulatorResponse()

        // to test the property `deliveryId`
        should("test deliveryId") {
            // uncomment below to test the property
            //modelInstance.deliveryId shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `latencyMs` - Response time from the endpoint
        should("test latencyMs") {
            // uncomment below to test the property
            //modelInstance.latencyMs shouldBe ("TODO")
        }

    }
}
