/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import hooksniff.models.ValidateEventResponse
import hooksniff.models.ValidateEventResponseErrorsInner

class ValidateEventResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidateEventResponse
        //val modelInstance = ValidateEventResponse()

        // to test the property `valid`
        should("test valid") {
            // uncomment below to test the property
            //modelInstance.valid shouldBe ("TODO")
        }

        // to test the property `errors`
        should("test errors") {
            // uncomment below to test the property
            //modelInstance.errors shouldBe ("TODO")
        }

    }
}
