/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`inbound_provider_endpoint_id_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InboundProviderEndpointIdPostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`inbound_provider_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InboundProviderPostError {
    Status400(),
    UnknownValue(serde_json::Value),
}


pub async fn inbound_provider_endpoint_id_post(configuration: &configuration::Configuration, provider: &str, endpoint_id: &str, body: serde_json::Value) -> Result<(), Error<InboundProviderEndpointIdPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_provider = provider;
    let p_path_endpoint_id = endpoint_id;
    let p_body_body = body;

    let uri_str = format!("{}/inbound/{provider}/{endpoint_id}", configuration.base_path, provider=crate::apis::urlencode(p_path_provider), endpoint_id=crate::apis::urlencode(p_path_endpoint_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<InboundProviderEndpointIdPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Accepts webhooks from external providers (Stripe, GitHub, etc.) and routes them to the customer's endpoints. 
pub async fn inbound_provider_post(configuration: &configuration::Configuration, provider: &str, body: serde_json::Value) -> Result<(), Error<InboundProviderPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_provider = provider;
    let p_body_body = body;

    let uri_str = format!("{}/inbound/{provider}", configuration.base_path, provider=crate::apis::urlencode(p_path_provider));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<InboundProviderPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

