# coding: utf-8

"""
    HookSniff API

    Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@hooksniff.vercel.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hooksniff.models.inbound_config import InboundConfig

class TestInboundConfig(unittest.TestCase):
    """InboundConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InboundConfig:
        """Test InboundConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InboundConfig`
        """
        model = InboundConfig()
        if include_optional:
            return InboundConfig(
                id = '',
                customer_id = '',
                provider = '',
                secret = '',
                endpoint_id = '',
                enabled = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return InboundConfig(
        )
        """

    def testInboundConfig(self):
        """Test InboundConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
