# coding: utf-8

"""
    HookSniff API

    Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@hooksniff.vercel.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hooksniff.models.create_api_key_response import CreateApiKeyResponse

class TestCreateApiKeyResponse(unittest.TestCase):
    """CreateApiKeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateApiKeyResponse:
        """Test CreateApiKeyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateApiKeyResponse`
        """
        model = CreateApiKeyResponse()
        if include_optional:
            return CreateApiKeyResponse(
                id = '',
                key = '',
                prefix = '',
                message = ''
            )
        else:
            return CreateApiKeyResponse(
                id = '',
                key = '',
                prefix = '',
                message = '',
        )
        """

    def testCreateApiKeyResponse(self):
        """Test CreateApiKeyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
