# coding: utf-8

"""
    HookSniff API

    Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@hooksniff.vercel.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hooksniff.models.register_device_request import RegisterDeviceRequest

class TestRegisterDeviceRequest(unittest.TestCase):
    """RegisterDeviceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisterDeviceRequest:
        """Test RegisterDeviceRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegisterDeviceRequest`
        """
        model = RegisterDeviceRequest()
        if include_optional:
            return RegisterDeviceRequest(
                token = '',
                platform = 'android'
            )
        else:
            return RegisterDeviceRequest(
                token = '',
        )
        """

    def testRegisterDeviceRequest(self):
        """Test RegisterDeviceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
