# coding: utf-8

"""
    HookSniff API

    Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@hooksniff.vercel.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hooksniff.models.alert_notification_list_response_data_inner import AlertNotificationListResponseDataInner

class TestAlertNotificationListResponseDataInner(unittest.TestCase):
    """AlertNotificationListResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlertNotificationListResponseDataInner:
        """Test AlertNotificationListResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlertNotificationListResponseDataInner`
        """
        model = AlertNotificationListResponseDataInner()
        if include_optional:
            return AlertNotificationListResponseDataInner(
                id = '',
                alert_rule_id = '',
                message = '',
                channel = '',
                status = 'sent',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AlertNotificationListResponseDataInner(
        )
        """

    def testAlertNotificationListResponseDataInner(self):
        """Test AlertNotificationListResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
