# coding: utf-8

"""
    HookSniff API

    Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@hooksniff.vercel.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hooksniff.models.admin_settings_put200_response import AdminSettingsPut200Response

class TestAdminSettingsPut200Response(unittest.TestCase):
    """AdminSettingsPut200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminSettingsPut200Response:
        """Test AdminSettingsPut200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminSettingsPut200Response`
        """
        model = AdminSettingsPut200Response()
        if include_optional:
            return AdminSettingsPut200Response(
                message = ''
            )
        else:
            return AdminSettingsPut200Response(
        )
        """

    def testAdminSettingsPut200Response(self):
        """Test AdminSettingsPut200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
