# coding: utf-8

"""
    HookSniff API

    Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@hooksniff.vercel.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hooksniff.api.notifications_api import NotificationsApi


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationsApi()

    def tearDown(self) -> None:
        pass

    def test_notifications_get(self) -> None:
        """Test case for notifications_get

        List notifications
        """
        pass

    def test_notifications_id_delete(self) -> None:
        """Test case for notifications_id_delete

        Delete notification
        """
        pass

    def test_notifications_id_read_put(self) -> None:
        """Test case for notifications_id_read_put

        Mark notification as read
        """
        pass

    def test_notifications_read_all_put(self) -> None:
        """Test case for notifications_read_all_put

        Mark all notifications as read
        """
        pass

    def test_notifications_unread_count_get(self) -> None:
        """Test case for notifications_unread_count_get

        Get unread notification count
        """
        pass


if __name__ == '__main__':
    unittest.main()
