# coding: utf-8

"""
    HookSniff API

    Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@hooksniff.vercel.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hooksniff.models.update_routing_request import UpdateRoutingRequest

class TestUpdateRoutingRequest(unittest.TestCase):
    """UpdateRoutingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateRoutingRequest:
        """Test UpdateRoutingRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateRoutingRequest`
        """
        model = UpdateRoutingRequest()
        if include_optional:
            return UpdateRoutingRequest(
                routing_strategy = 'round-robin',
                fallback_url = ''
            )
        else:
            return UpdateRoutingRequest(
                routing_strategy = 'round-robin',
                fallback_url = '',
        )
        """

    def testUpdateRoutingRequest(self):
        """Test UpdateRoutingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
