# coding: utf-8

"""
    HookSniff API

    Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@hooksniff.vercel.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hooksniff.api.alerts_api import AlertsApi


class TestAlertsApi(unittest.TestCase):
    """AlertsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AlertsApi()

    def tearDown(self) -> None:
        pass

    def test_alerts_get(self) -> None:
        """Test case for alerts_get

        List alert rules
        """
        pass

    def test_alerts_id_delete(self) -> None:
        """Test case for alerts_id_delete

        Delete alert rule
        """
        pass

    def test_alerts_id_get(self) -> None:
        """Test case for alerts_id_get

        Get alert rule
        """
        pass

    def test_alerts_id_test_post(self) -> None:
        """Test case for alerts_id_test_post

        Test an alert rule
        """
        pass

    def test_alerts_post(self) -> None:
        """Test case for alerts_post

        Create alert rule
        """
        pass


if __name__ == '__main__':
    unittest.main()
