APP_ENV: "production"
RUST_LOG: "info,hooksniff=info"
NOTIFY_FROM_EMAIL: "noreply@hooksniff.vercel.app"
OTEL_ENABLED: "true"
OTEL_EXPORTER_OTLP_ENDPOINT: "https://o4511400113471488.ingest.de.sentry.io/api/4511400117010512/integration/otlp"
