=begin
#HookSniff API

#Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

The version of the OpenAPI document: 1.0.0
Contact: support@hooksniff.vercel.app
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::Enable2faRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::Enable2faRequest do
  #let(:instance) { OpenapiClient::Enable2faRequest.new }

  describe 'test an instance of Enable2faRequest' do
    it 'should create an instance of Enable2faRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::Enable2faRequest)
    end
  end

  describe 'test attribute "password"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
