import { DashboardOverview } from './components/DashboardOverview';

/* ─── Server wrapper — delegates to client component ─── */
/* Client-reference-manifest is generated by fix-manifests.js post-build */

export default function DashboardPage() {
  return <DashboardOverview />;
}
