/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Endpoint {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(rename = "retry_policy", skip_serializing_if = "Option::is_none")]
    pub retry_policy: Option<Box<models::RetryPolicy>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// CIDR blocks or exact IPs
    #[serde(rename = "allowed_ips", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allowed_ips: Option<Option<Vec<String>>>,
    /// Wildcard patterns (e.g. \"order.*\")
    #[serde(rename = "event_filter", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub event_filter: Option<Option<Vec<String>>>,
    #[serde(rename = "custom_headers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_headers: Option<Option<serde_json::Value>>,
    #[serde(rename = "routing_strategy", skip_serializing_if = "Option::is_none")]
    pub routing_strategy: Option<RoutingStrategy>,
    #[serde(rename = "fallback_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fallback_url: Option<Option<String>>,
    #[serde(rename = "avg_response_ms", skip_serializing_if = "Option::is_none")]
    pub avg_response_ms: Option<i32>,
    #[serde(rename = "failure_streak", skip_serializing_if = "Option::is_none")]
    pub failure_streak: Option<i32>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<Format>,
}

impl Endpoint {
    pub fn new() -> Endpoint {
        Endpoint {
            id: None,
            url: None,
            description: None,
            is_active: None,
            retry_policy: None,
            created_at: None,
            allowed_ips: None,
            event_filter: None,
            custom_headers: None,
            routing_strategy: None,
            fallback_url: None,
            avg_response_ms: None,
            failure_streak: None,
            format: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RoutingStrategy {
    #[serde(rename = "round-robin")]
    RoundRobin,
    #[serde(rename = "latency")]
    Latency,
    #[serde(rename = "failover")]
    Failover,
}

impl Default for RoutingStrategy {
    fn default() -> RoutingStrategy {
        Self::RoundRobin
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Format {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "cloudevents")]
    Cloudevents,
}

impl Default for Format {
    fn default() -> Format {
        Self::Standard
    }
}

