/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamDetailResponse {
    #[serde(rename = "team", skip_serializing_if = "Option::is_none")]
    pub team: Option<Box<models::Team>>,
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<Vec<models::TeamMember>>,
    #[serde(rename = "invites", skip_serializing_if = "Option::is_none")]
    pub invites: Option<Vec<models::TeamInvite>>,
}

impl TeamDetailResponse {
    pub fn new() -> TeamDetailResponse {
        TeamDetailResponse {
            team: None,
            members: None,
            invites: None,
        }
    }
}

