=begin
#HookSniff API

#Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

The version of the OpenAPI document: 1.0.0
Contact: support@hooksniff.vercel.app
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module OpenapiClient
  # Platform-wide configuration settings
  class PlatformSettings < ApiModelBase
    attr_accessor :default_plan

    attr_accessor :max_endpoints_free

    attr_accessor :max_endpoints_pro

    attr_accessor :max_webhooks_free

    attr_accessor :max_webhooks_pro

    attr_accessor :rate_limit_free

    attr_accessor :rate_limit_pro

    attr_accessor :retry_max_attempts

    attr_accessor :retention_days_free

    attr_accessor :retention_days_pro

    attr_accessor :maintenance_mode

    attr_accessor :signup_enabled

    attr_accessor :plan_price_pro

    attr_accessor :plan_price_business

    attr_accessor :resend_api_key

    attr_accessor :email_sender

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'default_plan' => :'default_plan',
        :'max_endpoints_free' => :'max_endpoints_free',
        :'max_endpoints_pro' => :'max_endpoints_pro',
        :'max_webhooks_free' => :'max_webhooks_free',
        :'max_webhooks_pro' => :'max_webhooks_pro',
        :'rate_limit_free' => :'rate_limit_free',
        :'rate_limit_pro' => :'rate_limit_pro',
        :'retry_max_attempts' => :'retry_max_attempts',
        :'retention_days_free' => :'retention_days_free',
        :'retention_days_pro' => :'retention_days_pro',
        :'maintenance_mode' => :'maintenance_mode',
        :'signup_enabled' => :'signup_enabled',
        :'plan_price_pro' => :'plan_price_pro',
        :'plan_price_business' => :'plan_price_business',
        :'resend_api_key' => :'resend_api_key',
        :'email_sender' => :'email_sender'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'default_plan' => :'String',
        :'max_endpoints_free' => :'Integer',
        :'max_endpoints_pro' => :'Integer',
        :'max_webhooks_free' => :'Integer',
        :'max_webhooks_pro' => :'Integer',
        :'rate_limit_free' => :'Integer',
        :'rate_limit_pro' => :'Integer',
        :'retry_max_attempts' => :'Integer',
        :'retention_days_free' => :'Integer',
        :'retention_days_pro' => :'Integer',
        :'maintenance_mode' => :'Boolean',
        :'signup_enabled' => :'Boolean',
        :'plan_price_pro' => :'Float',
        :'plan_price_business' => :'Float',
        :'resend_api_key' => :'String',
        :'email_sender' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'resend_api_key',
        :'email_sender'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PlatformSettings` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PlatformSettings`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'default_plan')
        self.default_plan = attributes[:'default_plan']
      else
        self.default_plan = nil
      end

      if attributes.key?(:'max_endpoints_free')
        self.max_endpoints_free = attributes[:'max_endpoints_free']
      else
        self.max_endpoints_free = nil
      end

      if attributes.key?(:'max_endpoints_pro')
        self.max_endpoints_pro = attributes[:'max_endpoints_pro']
      else
        self.max_endpoints_pro = nil
      end

      if attributes.key?(:'max_webhooks_free')
        self.max_webhooks_free = attributes[:'max_webhooks_free']
      else
        self.max_webhooks_free = nil
      end

      if attributes.key?(:'max_webhooks_pro')
        self.max_webhooks_pro = attributes[:'max_webhooks_pro']
      else
        self.max_webhooks_pro = nil
      end

      if attributes.key?(:'rate_limit_free')
        self.rate_limit_free = attributes[:'rate_limit_free']
      else
        self.rate_limit_free = nil
      end

      if attributes.key?(:'rate_limit_pro')
        self.rate_limit_pro = attributes[:'rate_limit_pro']
      else
        self.rate_limit_pro = nil
      end

      if attributes.key?(:'retry_max_attempts')
        self.retry_max_attempts = attributes[:'retry_max_attempts']
      else
        self.retry_max_attempts = nil
      end

      if attributes.key?(:'retention_days_free')
        self.retention_days_free = attributes[:'retention_days_free']
      else
        self.retention_days_free = nil
      end

      if attributes.key?(:'retention_days_pro')
        self.retention_days_pro = attributes[:'retention_days_pro']
      else
        self.retention_days_pro = nil
      end

      if attributes.key?(:'maintenance_mode')
        self.maintenance_mode = attributes[:'maintenance_mode']
      else
        self.maintenance_mode = nil
      end

      if attributes.key?(:'signup_enabled')
        self.signup_enabled = attributes[:'signup_enabled']
      else
        self.signup_enabled = nil
      end

      if attributes.key?(:'plan_price_pro')
        self.plan_price_pro = attributes[:'plan_price_pro']
      else
        self.plan_price_pro = nil
      end

      if attributes.key?(:'plan_price_business')
        self.plan_price_business = attributes[:'plan_price_business']
      else
        self.plan_price_business = nil
      end

      if attributes.key?(:'resend_api_key')
        self.resend_api_key = attributes[:'resend_api_key']
      end

      if attributes.key?(:'email_sender')
        self.email_sender = attributes[:'email_sender']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @default_plan.nil?
        invalid_properties.push('invalid value for "default_plan", default_plan cannot be nil.')
      end

      if @max_endpoints_free.nil?
        invalid_properties.push('invalid value for "max_endpoints_free", max_endpoints_free cannot be nil.')
      end

      if @max_endpoints_pro.nil?
        invalid_properties.push('invalid value for "max_endpoints_pro", max_endpoints_pro cannot be nil.')
      end

      if @max_webhooks_free.nil?
        invalid_properties.push('invalid value for "max_webhooks_free", max_webhooks_free cannot be nil.')
      end

      if @max_webhooks_pro.nil?
        invalid_properties.push('invalid value for "max_webhooks_pro", max_webhooks_pro cannot be nil.')
      end

      if @rate_limit_free.nil?
        invalid_properties.push('invalid value for "rate_limit_free", rate_limit_free cannot be nil.')
      end

      if @rate_limit_pro.nil?
        invalid_properties.push('invalid value for "rate_limit_pro", rate_limit_pro cannot be nil.')
      end

      if @retry_max_attempts.nil?
        invalid_properties.push('invalid value for "retry_max_attempts", retry_max_attempts cannot be nil.')
      end

      if @retention_days_free.nil?
        invalid_properties.push('invalid value for "retention_days_free", retention_days_free cannot be nil.')
      end

      if @retention_days_pro.nil?
        invalid_properties.push('invalid value for "retention_days_pro", retention_days_pro cannot be nil.')
      end

      if @maintenance_mode.nil?
        invalid_properties.push('invalid value for "maintenance_mode", maintenance_mode cannot be nil.')
      end

      if @signup_enabled.nil?
        invalid_properties.push('invalid value for "signup_enabled", signup_enabled cannot be nil.')
      end

      if @plan_price_pro.nil?
        invalid_properties.push('invalid value for "plan_price_pro", plan_price_pro cannot be nil.')
      end

      if @plan_price_business.nil?
        invalid_properties.push('invalid value for "plan_price_business", plan_price_business cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @default_plan.nil?
      return false if @max_endpoints_free.nil?
      return false if @max_endpoints_pro.nil?
      return false if @max_webhooks_free.nil?
      return false if @max_webhooks_pro.nil?
      return false if @rate_limit_free.nil?
      return false if @rate_limit_pro.nil?
      return false if @retry_max_attempts.nil?
      return false if @retention_days_free.nil?
      return false if @retention_days_pro.nil?
      return false if @maintenance_mode.nil?
      return false if @signup_enabled.nil?
      return false if @plan_price_pro.nil?
      return false if @plan_price_business.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] default_plan Value to be assigned
    def default_plan=(default_plan)
      if default_plan.nil?
        fail ArgumentError, 'default_plan cannot be nil'
      end

      @default_plan = default_plan
    end

    # Custom attribute writer method with validation
    # @param [Object] max_endpoints_free Value to be assigned
    def max_endpoints_free=(max_endpoints_free)
      if max_endpoints_free.nil?
        fail ArgumentError, 'max_endpoints_free cannot be nil'
      end

      @max_endpoints_free = max_endpoints_free
    end

    # Custom attribute writer method with validation
    # @param [Object] max_endpoints_pro Value to be assigned
    def max_endpoints_pro=(max_endpoints_pro)
      if max_endpoints_pro.nil?
        fail ArgumentError, 'max_endpoints_pro cannot be nil'
      end

      @max_endpoints_pro = max_endpoints_pro
    end

    # Custom attribute writer method with validation
    # @param [Object] max_webhooks_free Value to be assigned
    def max_webhooks_free=(max_webhooks_free)
      if max_webhooks_free.nil?
        fail ArgumentError, 'max_webhooks_free cannot be nil'
      end

      @max_webhooks_free = max_webhooks_free
    end

    # Custom attribute writer method with validation
    # @param [Object] max_webhooks_pro Value to be assigned
    def max_webhooks_pro=(max_webhooks_pro)
      if max_webhooks_pro.nil?
        fail ArgumentError, 'max_webhooks_pro cannot be nil'
      end

      @max_webhooks_pro = max_webhooks_pro
    end

    # Custom attribute writer method with validation
    # @param [Object] rate_limit_free Value to be assigned
    def rate_limit_free=(rate_limit_free)
      if rate_limit_free.nil?
        fail ArgumentError, 'rate_limit_free cannot be nil'
      end

      @rate_limit_free = rate_limit_free
    end

    # Custom attribute writer method with validation
    # @param [Object] rate_limit_pro Value to be assigned
    def rate_limit_pro=(rate_limit_pro)
      if rate_limit_pro.nil?
        fail ArgumentError, 'rate_limit_pro cannot be nil'
      end

      @rate_limit_pro = rate_limit_pro
    end

    # Custom attribute writer method with validation
    # @param [Object] retry_max_attempts Value to be assigned
    def retry_max_attempts=(retry_max_attempts)
      if retry_max_attempts.nil?
        fail ArgumentError, 'retry_max_attempts cannot be nil'
      end

      @retry_max_attempts = retry_max_attempts
    end

    # Custom attribute writer method with validation
    # @param [Object] retention_days_free Value to be assigned
    def retention_days_free=(retention_days_free)
      if retention_days_free.nil?
        fail ArgumentError, 'retention_days_free cannot be nil'
      end

      @retention_days_free = retention_days_free
    end

    # Custom attribute writer method with validation
    # @param [Object] retention_days_pro Value to be assigned
    def retention_days_pro=(retention_days_pro)
      if retention_days_pro.nil?
        fail ArgumentError, 'retention_days_pro cannot be nil'
      end

      @retention_days_pro = retention_days_pro
    end

    # Custom attribute writer method with validation
    # @param [Object] maintenance_mode Value to be assigned
    def maintenance_mode=(maintenance_mode)
      if maintenance_mode.nil?
        fail ArgumentError, 'maintenance_mode cannot be nil'
      end

      @maintenance_mode = maintenance_mode
    end

    # Custom attribute writer method with validation
    # @param [Object] signup_enabled Value to be assigned
    def signup_enabled=(signup_enabled)
      if signup_enabled.nil?
        fail ArgumentError, 'signup_enabled cannot be nil'
      end

      @signup_enabled = signup_enabled
    end

    # Custom attribute writer method with validation
    # @param [Object] plan_price_pro Value to be assigned
    def plan_price_pro=(plan_price_pro)
      if plan_price_pro.nil?
        fail ArgumentError, 'plan_price_pro cannot be nil'
      end

      @plan_price_pro = plan_price_pro
    end

    # Custom attribute writer method with validation
    # @param [Object] plan_price_business Value to be assigned
    def plan_price_business=(plan_price_business)
      if plan_price_business.nil?
        fail ArgumentError, 'plan_price_business cannot be nil'
      end

      @plan_price_business = plan_price_business
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          default_plan == o.default_plan &&
          max_endpoints_free == o.max_endpoints_free &&
          max_endpoints_pro == o.max_endpoints_pro &&
          max_webhooks_free == o.max_webhooks_free &&
          max_webhooks_pro == o.max_webhooks_pro &&
          rate_limit_free == o.rate_limit_free &&
          rate_limit_pro == o.rate_limit_pro &&
          retry_max_attempts == o.retry_max_attempts &&
          retention_days_free == o.retention_days_free &&
          retention_days_pro == o.retention_days_pro &&
          maintenance_mode == o.maintenance_mode &&
          signup_enabled == o.signup_enabled &&
          plan_price_pro == o.plan_price_pro &&
          plan_price_business == o.plan_price_business &&
          resend_api_key == o.resend_api_key &&
          email_sender == o.email_sender
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [default_plan, max_endpoints_free, max_endpoints_pro, max_webhooks_free, max_webhooks_pro, rate_limit_free, rate_limit_pro, retry_max_attempts, retention_days_free, retention_days_pro, maintenance_mode, signup_enabled, plan_price_pro, plan_price_business, resend_api_key, email_sender].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
