/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package hooksniff.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param provider 
 * @param enabled 
 */


data class SsoConfigPostRequest (

    @Json(name = "provider")
    val provider: SsoConfigPostRequest.Provider? = null,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: saml,oidc
     */
    @JsonClass(generateAdapter = false)
    enum class Provider(val value: kotlin.String) {
        @Json(name = "saml") saml("saml"),
        @Json(name = "oidc") oidc("oidc");
    }

}

