/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"time"
)

// checks if the Auth2faStatusGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Auth2faStatusGet200Response{}

// Auth2faStatusGet200Response struct for Auth2faStatusGet200Response
type Auth2faStatusGet200Response struct {
	Enabled *bool `json:"enabled,omitempty"`
	LastUsedAt NullableTime `json:"last_used_at,omitempty"`
}

// NewAuth2faStatusGet200Response instantiates a new Auth2faStatusGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuth2faStatusGet200Response() *Auth2faStatusGet200Response {
	this := Auth2faStatusGet200Response{}
	return &this
}

// NewAuth2faStatusGet200ResponseWithDefaults instantiates a new Auth2faStatusGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuth2faStatusGet200ResponseWithDefaults() *Auth2faStatusGet200Response {
	this := Auth2faStatusGet200Response{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *Auth2faStatusGet200Response) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth2faStatusGet200Response) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *Auth2faStatusGet200Response) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *Auth2faStatusGet200Response) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Auth2faStatusGet200Response) GetLastUsedAt() time.Time {
	if o == nil || IsNil(o.LastUsedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastUsedAt.Get()
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Auth2faStatusGet200Response) GetLastUsedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUsedAt.Get(), o.LastUsedAt.IsSet()
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *Auth2faStatusGet200Response) HasLastUsedAt() bool {
	if o != nil && o.LastUsedAt.IsSet() {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given NullableTime and assigns it to the LastUsedAt field.
func (o *Auth2faStatusGet200Response) SetLastUsedAt(v time.Time) {
	o.LastUsedAt.Set(&v)
}
// SetLastUsedAtNil sets the value for LastUsedAt to be an explicit nil
func (o *Auth2faStatusGet200Response) SetLastUsedAtNil() {
	o.LastUsedAt.Set(nil)
}

// UnsetLastUsedAt ensures that no value is present for LastUsedAt, not even an explicit nil
func (o *Auth2faStatusGet200Response) UnsetLastUsedAt() {
	o.LastUsedAt.Unset()
}

func (o Auth2faStatusGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Auth2faStatusGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if o.LastUsedAt.IsSet() {
		toSerialize["last_used_at"] = o.LastUsedAt.Get()
	}
	return toSerialize, nil
}

type NullableAuth2faStatusGet200Response struct {
	value *Auth2faStatusGet200Response
	isSet bool
}

func (v NullableAuth2faStatusGet200Response) Get() *Auth2faStatusGet200Response {
	return v.value
}

func (v *NullableAuth2faStatusGet200Response) Set(val *Auth2faStatusGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAuth2faStatusGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAuth2faStatusGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuth2faStatusGet200Response(val *Auth2faStatusGet200Response) *NullableAuth2faStatusGet200Response {
	return &NullableAuth2faStatusGet200Response{value: val, isSet: true}
}

func (v NullableAuth2faStatusGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuth2faStatusGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


