/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DeliveryAttempt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliveryAttempt{}

// DeliveryAttempt struct for DeliveryAttempt
type DeliveryAttempt struct {
	Id string `json:"id"`
	AttemptNumber int32 `json:"attempt_number"`
	StatusCode NullableInt32 `json:"status_code,omitempty"`
	ResponseBody NullableString `json:"response_body,omitempty"`
	DurationMs NullableInt32 `json:"duration_ms,omitempty"`
	ErrorMessage NullableString `json:"error_message,omitempty"`
	CreatedAt time.Time `json:"created_at"`
}

type _DeliveryAttempt DeliveryAttempt

// NewDeliveryAttempt instantiates a new DeliveryAttempt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryAttempt(id string, attemptNumber int32, createdAt time.Time) *DeliveryAttempt {
	this := DeliveryAttempt{}
	this.Id = id
	this.AttemptNumber = attemptNumber
	this.CreatedAt = createdAt
	return &this
}

// NewDeliveryAttemptWithDefaults instantiates a new DeliveryAttempt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryAttemptWithDefaults() *DeliveryAttempt {
	this := DeliveryAttempt{}
	return &this
}

// GetId returns the Id field value
func (o *DeliveryAttempt) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeliveryAttempt) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeliveryAttempt) SetId(v string) {
	o.Id = v
}

// GetAttemptNumber returns the AttemptNumber field value
func (o *DeliveryAttempt) GetAttemptNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AttemptNumber
}

// GetAttemptNumberOk returns a tuple with the AttemptNumber field value
// and a boolean to check if the value has been set.
func (o *DeliveryAttempt) GetAttemptNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttemptNumber, true
}

// SetAttemptNumber sets field value
func (o *DeliveryAttempt) SetAttemptNumber(v int32) {
	o.AttemptNumber = v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryAttempt) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode.Get()) {
		var ret int32
		return ret
	}
	return *o.StatusCode.Get()
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryAttempt) GetStatusCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatusCode.Get(), o.StatusCode.IsSet()
}

// HasStatusCode returns a boolean if a field has been set.
func (o *DeliveryAttempt) HasStatusCode() bool {
	if o != nil && o.StatusCode.IsSet() {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given NullableInt32 and assigns it to the StatusCode field.
func (o *DeliveryAttempt) SetStatusCode(v int32) {
	o.StatusCode.Set(&v)
}
// SetStatusCodeNil sets the value for StatusCode to be an explicit nil
func (o *DeliveryAttempt) SetStatusCodeNil() {
	o.StatusCode.Set(nil)
}

// UnsetStatusCode ensures that no value is present for StatusCode, not even an explicit nil
func (o *DeliveryAttempt) UnsetStatusCode() {
	o.StatusCode.Unset()
}

// GetResponseBody returns the ResponseBody field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryAttempt) GetResponseBody() string {
	if o == nil || IsNil(o.ResponseBody.Get()) {
		var ret string
		return ret
	}
	return *o.ResponseBody.Get()
}

// GetResponseBodyOk returns a tuple with the ResponseBody field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryAttempt) GetResponseBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResponseBody.Get(), o.ResponseBody.IsSet()
}

// HasResponseBody returns a boolean if a field has been set.
func (o *DeliveryAttempt) HasResponseBody() bool {
	if o != nil && o.ResponseBody.IsSet() {
		return true
	}

	return false
}

// SetResponseBody gets a reference to the given NullableString and assigns it to the ResponseBody field.
func (o *DeliveryAttempt) SetResponseBody(v string) {
	o.ResponseBody.Set(&v)
}
// SetResponseBodyNil sets the value for ResponseBody to be an explicit nil
func (o *DeliveryAttempt) SetResponseBodyNil() {
	o.ResponseBody.Set(nil)
}

// UnsetResponseBody ensures that no value is present for ResponseBody, not even an explicit nil
func (o *DeliveryAttempt) UnsetResponseBody() {
	o.ResponseBody.Unset()
}

// GetDurationMs returns the DurationMs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryAttempt) GetDurationMs() int32 {
	if o == nil || IsNil(o.DurationMs.Get()) {
		var ret int32
		return ret
	}
	return *o.DurationMs.Get()
}

// GetDurationMsOk returns a tuple with the DurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryAttempt) GetDurationMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DurationMs.Get(), o.DurationMs.IsSet()
}

// HasDurationMs returns a boolean if a field has been set.
func (o *DeliveryAttempt) HasDurationMs() bool {
	if o != nil && o.DurationMs.IsSet() {
		return true
	}

	return false
}

// SetDurationMs gets a reference to the given NullableInt32 and assigns it to the DurationMs field.
func (o *DeliveryAttempt) SetDurationMs(v int32) {
	o.DurationMs.Set(&v)
}
// SetDurationMsNil sets the value for DurationMs to be an explicit nil
func (o *DeliveryAttempt) SetDurationMsNil() {
	o.DurationMs.Set(nil)
}

// UnsetDurationMs ensures that no value is present for DurationMs, not even an explicit nil
func (o *DeliveryAttempt) UnsetDurationMs() {
	o.DurationMs.Unset()
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryAttempt) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorMessage.Get()
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryAttempt) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorMessage.Get(), o.ErrorMessage.IsSet()
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *DeliveryAttempt) HasErrorMessage() bool {
	if o != nil && o.ErrorMessage.IsSet() {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given NullableString and assigns it to the ErrorMessage field.
func (o *DeliveryAttempt) SetErrorMessage(v string) {
	o.ErrorMessage.Set(&v)
}
// SetErrorMessageNil sets the value for ErrorMessage to be an explicit nil
func (o *DeliveryAttempt) SetErrorMessageNil() {
	o.ErrorMessage.Set(nil)
}

// UnsetErrorMessage ensures that no value is present for ErrorMessage, not even an explicit nil
func (o *DeliveryAttempt) UnsetErrorMessage() {
	o.ErrorMessage.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *DeliveryAttempt) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DeliveryAttempt) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DeliveryAttempt) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o DeliveryAttempt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliveryAttempt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["attempt_number"] = o.AttemptNumber
	if o.StatusCode.IsSet() {
		toSerialize["status_code"] = o.StatusCode.Get()
	}
	if o.ResponseBody.IsSet() {
		toSerialize["response_body"] = o.ResponseBody.Get()
	}
	if o.DurationMs.IsSet() {
		toSerialize["duration_ms"] = o.DurationMs.Get()
	}
	if o.ErrorMessage.IsSet() {
		toSerialize["error_message"] = o.ErrorMessage.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *DeliveryAttempt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"attempt_number",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeliveryAttempt := _DeliveryAttempt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeliveryAttempt)

	if err != nil {
		return err
	}

	*o = DeliveryAttempt(varDeliveryAttempt)

	return err
}

type NullableDeliveryAttempt struct {
	value *DeliveryAttempt
	isSet bool
}

func (v NullableDeliveryAttempt) Get() *DeliveryAttempt {
	return v.value
}

func (v *NullableDeliveryAttempt) Set(val *DeliveryAttempt) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryAttempt) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryAttempt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryAttempt(val *DeliveryAttempt) *NullableDeliveryAttempt {
	return &NullableDeliveryAttempt{value: val, isSet: true}
}

func (v NullableDeliveryAttempt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryAttempt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


