/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AdminAlertRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminAlertRule{}

// AdminAlertRule Admin alert rule with customer info
type AdminAlertRule struct {
	Id string `json:"id"`
	CustomerId *string `json:"customer_id,omitempty"`
	CustomerEmail NullableString `json:"customer_email,omitempty"`
	Name string `json:"name"`
	Condition string `json:"condition"`
	Threshold int32 `json:"threshold"`
	Channels []string `json:"channels"`
	IsActive bool `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type _AdminAlertRule AdminAlertRule

// NewAdminAlertRule instantiates a new AdminAlertRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminAlertRule(id string, name string, condition string, threshold int32, channels []string, isActive bool, createdAt time.Time) *AdminAlertRule {
	this := AdminAlertRule{}
	this.Id = id
	this.Name = name
	this.Condition = condition
	this.Threshold = threshold
	this.Channels = channels
	this.IsActive = isActive
	this.CreatedAt = createdAt
	return &this
}

// NewAdminAlertRuleWithDefaults instantiates a new AdminAlertRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminAlertRuleWithDefaults() *AdminAlertRule {
	this := AdminAlertRule{}
	return &this
}

// GetId returns the Id field value
func (o *AdminAlertRule) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AdminAlertRule) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AdminAlertRule) SetId(v string) {
	o.Id = v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *AdminAlertRule) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminAlertRule) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *AdminAlertRule) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *AdminAlertRule) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetCustomerEmail returns the CustomerEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AdminAlertRule) GetCustomerEmail() string {
	if o == nil || IsNil(o.CustomerEmail.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerEmail.Get()
}

// GetCustomerEmailOk returns a tuple with the CustomerEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AdminAlertRule) GetCustomerEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerEmail.Get(), o.CustomerEmail.IsSet()
}

// HasCustomerEmail returns a boolean if a field has been set.
func (o *AdminAlertRule) HasCustomerEmail() bool {
	if o != nil && o.CustomerEmail.IsSet() {
		return true
	}

	return false
}

// SetCustomerEmail gets a reference to the given NullableString and assigns it to the CustomerEmail field.
func (o *AdminAlertRule) SetCustomerEmail(v string) {
	o.CustomerEmail.Set(&v)
}
// SetCustomerEmailNil sets the value for CustomerEmail to be an explicit nil
func (o *AdminAlertRule) SetCustomerEmailNil() {
	o.CustomerEmail.Set(nil)
}

// UnsetCustomerEmail ensures that no value is present for CustomerEmail, not even an explicit nil
func (o *AdminAlertRule) UnsetCustomerEmail() {
	o.CustomerEmail.Unset()
}

// GetName returns the Name field value
func (o *AdminAlertRule) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AdminAlertRule) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AdminAlertRule) SetName(v string) {
	o.Name = v
}

// GetCondition returns the Condition field value
func (o *AdminAlertRule) GetCondition() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Condition
}

// GetConditionOk returns a tuple with the Condition field value
// and a boolean to check if the value has been set.
func (o *AdminAlertRule) GetConditionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Condition, true
}

// SetCondition sets field value
func (o *AdminAlertRule) SetCondition(v string) {
	o.Condition = v
}

// GetThreshold returns the Threshold field value
func (o *AdminAlertRule) GetThreshold() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value
// and a boolean to check if the value has been set.
func (o *AdminAlertRule) GetThresholdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Threshold, true
}

// SetThreshold sets field value
func (o *AdminAlertRule) SetThreshold(v int32) {
	o.Threshold = v
}

// GetChannels returns the Channels field value
func (o *AdminAlertRule) GetChannels() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value
// and a boolean to check if the value has been set.
func (o *AdminAlertRule) GetChannelsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Channels, true
}

// SetChannels sets field value
func (o *AdminAlertRule) SetChannels(v []string) {
	o.Channels = v
}

// GetIsActive returns the IsActive field value
func (o *AdminAlertRule) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *AdminAlertRule) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *AdminAlertRule) SetIsActive(v bool) {
	o.IsActive = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AdminAlertRule) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AdminAlertRule) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AdminAlertRule) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o AdminAlertRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminAlertRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.CustomerId) {
		toSerialize["customer_id"] = o.CustomerId
	}
	if o.CustomerEmail.IsSet() {
		toSerialize["customer_email"] = o.CustomerEmail.Get()
	}
	toSerialize["name"] = o.Name
	toSerialize["condition"] = o.Condition
	toSerialize["threshold"] = o.Threshold
	toSerialize["channels"] = o.Channels
	toSerialize["is_active"] = o.IsActive
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *AdminAlertRule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"condition",
		"threshold",
		"channels",
		"is_active",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminAlertRule := _AdminAlertRule{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdminAlertRule)

	if err != nil {
		return err
	}

	*o = AdminAlertRule(varAdminAlertRule)

	return err
}

type NullableAdminAlertRule struct {
	value *AdminAlertRule
	isSet bool
}

func (v NullableAdminAlertRule) Get() *AdminAlertRule {
	return v.value
}

func (v *NullableAdminAlertRule) Set(val *AdminAlertRule) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminAlertRule) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminAlertRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminAlertRule(val *AdminAlertRule) *NullableAdminAlertRule {
	return &NullableAdminAlertRule{value: val, isSet: true}
}

func (v NullableAdminAlertRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminAlertRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


