/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RoutingRuleListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoutingRuleListResponse{}

// RoutingRuleListResponse List of routing rules
type RoutingRuleListResponse struct {
	Data []RoutingRuleListResponseDataInner `json:"data"`
}

type _RoutingRuleListResponse RoutingRuleListResponse

// NewRoutingRuleListResponse instantiates a new RoutingRuleListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutingRuleListResponse(data []RoutingRuleListResponseDataInner) *RoutingRuleListResponse {
	this := RoutingRuleListResponse{}
	this.Data = data
	return &this
}

// NewRoutingRuleListResponseWithDefaults instantiates a new RoutingRuleListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutingRuleListResponseWithDefaults() *RoutingRuleListResponse {
	this := RoutingRuleListResponse{}
	return &this
}

// GetData returns the Data field value
func (o *RoutingRuleListResponse) GetData() []RoutingRuleListResponseDataInner {
	if o == nil {
		var ret []RoutingRuleListResponseDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RoutingRuleListResponse) GetDataOk() ([]RoutingRuleListResponseDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *RoutingRuleListResponse) SetData(v []RoutingRuleListResponseDataInner) {
	o.Data = v
}

func (o RoutingRuleListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoutingRuleListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *RoutingRuleListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoutingRuleListResponse := _RoutingRuleListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRoutingRuleListResponse)

	if err != nil {
		return err
	}

	*o = RoutingRuleListResponse(varRoutingRuleListResponse)

	return err
}

type NullableRoutingRuleListResponse struct {
	value *RoutingRuleListResponse
	isSet bool
}

func (v NullableRoutingRuleListResponse) Get() *RoutingRuleListResponse {
	return v.value
}

func (v *NullableRoutingRuleListResponse) Set(val *RoutingRuleListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutingRuleListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutingRuleListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutingRuleListResponse(val *RoutingRuleListResponse) *NullableRoutingRuleListResponse {
	return &NullableRoutingRuleListResponse{value: val, isSet: true}
}

func (v NullableRoutingRuleListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutingRuleListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


