/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingPortalResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingPortalResponse{}

// BillingPortalResponse URL for the customer billing portal
type BillingPortalResponse struct {
	// Stripe billing portal URL
	Url string `json:"url"`
}

type _BillingPortalResponse BillingPortalResponse

// NewBillingPortalResponse instantiates a new BillingPortalResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingPortalResponse(url string) *BillingPortalResponse {
	this := BillingPortalResponse{}
	this.Url = url
	return &this
}

// NewBillingPortalResponseWithDefaults instantiates a new BillingPortalResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingPortalResponseWithDefaults() *BillingPortalResponse {
	this := BillingPortalResponse{}
	return &this
}

// GetUrl returns the Url field value
func (o *BillingPortalResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *BillingPortalResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *BillingPortalResponse) SetUrl(v string) {
	o.Url = v
}

func (o BillingPortalResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingPortalResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *BillingPortalResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingPortalResponse := _BillingPortalResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingPortalResponse)

	if err != nil {
		return err
	}

	*o = BillingPortalResponse(varBillingPortalResponse)

	return err
}

type NullableBillingPortalResponse struct {
	value *BillingPortalResponse
	isSet bool
}

func (v NullableBillingPortalResponse) Get() *BillingPortalResponse {
	return v.value
}

func (v *NullableBillingPortalResponse) Set(val *BillingPortalResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingPortalResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingPortalResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingPortalResponse(val *BillingPortalResponse) *NullableBillingPortalResponse {
	return &NullableBillingPortalResponse{value: val, isSet: true}
}

func (v NullableBillingPortalResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingPortalResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


