/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAlertRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAlertRuleRequest{}

// CreateAlertRuleRequest Request to create a new alert rule
type CreateAlertRuleRequest struct {
	// Human-readable alert name
	Name string `json:"name"`
	// Condition that triggers the alert
	Condition string `json:"condition"`
	// Threshold value for the condition
	Threshold int32 `json:"threshold"`
	// Notification channels to alert on
	Channels []string `json:"channels"`
}

type _CreateAlertRuleRequest CreateAlertRuleRequest

// NewCreateAlertRuleRequest instantiates a new CreateAlertRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAlertRuleRequest(name string, condition string, threshold int32, channels []string) *CreateAlertRuleRequest {
	this := CreateAlertRuleRequest{}
	this.Name = name
	this.Condition = condition
	this.Threshold = threshold
	this.Channels = channels
	return &this
}

// NewCreateAlertRuleRequestWithDefaults instantiates a new CreateAlertRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAlertRuleRequestWithDefaults() *CreateAlertRuleRequest {
	this := CreateAlertRuleRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateAlertRuleRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAlertRuleRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAlertRuleRequest) SetName(v string) {
	o.Name = v
}

// GetCondition returns the Condition field value
func (o *CreateAlertRuleRequest) GetCondition() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Condition
}

// GetConditionOk returns a tuple with the Condition field value
// and a boolean to check if the value has been set.
func (o *CreateAlertRuleRequest) GetConditionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Condition, true
}

// SetCondition sets field value
func (o *CreateAlertRuleRequest) SetCondition(v string) {
	o.Condition = v
}

// GetThreshold returns the Threshold field value
func (o *CreateAlertRuleRequest) GetThreshold() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value
// and a boolean to check if the value has been set.
func (o *CreateAlertRuleRequest) GetThresholdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Threshold, true
}

// SetThreshold sets field value
func (o *CreateAlertRuleRequest) SetThreshold(v int32) {
	o.Threshold = v
}

// GetChannels returns the Channels field value
func (o *CreateAlertRuleRequest) GetChannels() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value
// and a boolean to check if the value has been set.
func (o *CreateAlertRuleRequest) GetChannelsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Channels, true
}

// SetChannels sets field value
func (o *CreateAlertRuleRequest) SetChannels(v []string) {
	o.Channels = v
}

func (o CreateAlertRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAlertRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["condition"] = o.Condition
	toSerialize["threshold"] = o.Threshold
	toSerialize["channels"] = o.Channels
	return toSerialize, nil
}

func (o *CreateAlertRuleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"condition",
		"threshold",
		"channels",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAlertRuleRequest := _CreateAlertRuleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAlertRuleRequest)

	if err != nil {
		return err
	}

	*o = CreateAlertRuleRequest(varCreateAlertRuleRequest)

	return err
}

type NullableCreateAlertRuleRequest struct {
	value *CreateAlertRuleRequest
	isSet bool
}

func (v NullableCreateAlertRuleRequest) Get() *CreateAlertRuleRequest {
	return v.value
}

func (v *NullableCreateAlertRuleRequest) Set(val *CreateAlertRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAlertRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAlertRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAlertRuleRequest(val *CreateAlertRuleRequest) *NullableCreateAlertRuleRequest {
	return &NullableCreateAlertRuleRequest{value: val, isSet: true}
}

func (v NullableCreateAlertRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAlertRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


