/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdminTestWebhookResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminTestWebhookResponse{}

// AdminTestWebhookResponse Result of a test webhook delivery
type AdminTestWebhookResponse struct {
	StatusCode int32 `json:"status_code"`
	ResponseBody string `json:"response_body"`
	DurationMs int32 `json:"duration_ms"`
}

type _AdminTestWebhookResponse AdminTestWebhookResponse

// NewAdminTestWebhookResponse instantiates a new AdminTestWebhookResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminTestWebhookResponse(statusCode int32, responseBody string, durationMs int32) *AdminTestWebhookResponse {
	this := AdminTestWebhookResponse{}
	this.StatusCode = statusCode
	this.ResponseBody = responseBody
	this.DurationMs = durationMs
	return &this
}

// NewAdminTestWebhookResponseWithDefaults instantiates a new AdminTestWebhookResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminTestWebhookResponseWithDefaults() *AdminTestWebhookResponse {
	this := AdminTestWebhookResponse{}
	return &this
}

// GetStatusCode returns the StatusCode field value
func (o *AdminTestWebhookResponse) GetStatusCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value
// and a boolean to check if the value has been set.
func (o *AdminTestWebhookResponse) GetStatusCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusCode, true
}

// SetStatusCode sets field value
func (o *AdminTestWebhookResponse) SetStatusCode(v int32) {
	o.StatusCode = v
}

// GetResponseBody returns the ResponseBody field value
func (o *AdminTestWebhookResponse) GetResponseBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResponseBody
}

// GetResponseBodyOk returns a tuple with the ResponseBody field value
// and a boolean to check if the value has been set.
func (o *AdminTestWebhookResponse) GetResponseBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResponseBody, true
}

// SetResponseBody sets field value
func (o *AdminTestWebhookResponse) SetResponseBody(v string) {
	o.ResponseBody = v
}

// GetDurationMs returns the DurationMs field value
func (o *AdminTestWebhookResponse) GetDurationMs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DurationMs
}

// GetDurationMsOk returns a tuple with the DurationMs field value
// and a boolean to check if the value has been set.
func (o *AdminTestWebhookResponse) GetDurationMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationMs, true
}

// SetDurationMs sets field value
func (o *AdminTestWebhookResponse) SetDurationMs(v int32) {
	o.DurationMs = v
}

func (o AdminTestWebhookResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminTestWebhookResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status_code"] = o.StatusCode
	toSerialize["response_body"] = o.ResponseBody
	toSerialize["duration_ms"] = o.DurationMs
	return toSerialize, nil
}

func (o *AdminTestWebhookResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status_code",
		"response_body",
		"duration_ms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminTestWebhookResponse := _AdminTestWebhookResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdminTestWebhookResponse)

	if err != nil {
		return err
	}

	*o = AdminTestWebhookResponse(varAdminTestWebhookResponse)

	return err
}

type NullableAdminTestWebhookResponse struct {
	value *AdminTestWebhookResponse
	isSet bool
}

func (v NullableAdminTestWebhookResponse) Get() *AdminTestWebhookResponse {
	return v.value
}

func (v *NullableAdminTestWebhookResponse) Set(val *AdminTestWebhookResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminTestWebhookResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminTestWebhookResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminTestWebhookResponse(val *AdminTestWebhookResponse) *NullableAdminTestWebhookResponse {
	return &NullableAdminTestWebhookResponse{value: val, isSet: true}
}

func (v NullableAdminTestWebhookResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminTestWebhookResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


