/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ChurnedUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChurnedUser{}

// ChurnedUser A user who churned (became inactive) recently
type ChurnedUser struct {
	Id string `json:"id"`
	Email string `json:"email"`
	Name NullableString `json:"name,omitempty"`
	Plan string `json:"plan"`
	Amount float64 `json:"amount"`
	ChurnDate time.Time `json:"churn_date"`
}

type _ChurnedUser ChurnedUser

// NewChurnedUser instantiates a new ChurnedUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChurnedUser(id string, email string, plan string, amount float64, churnDate time.Time) *ChurnedUser {
	this := ChurnedUser{}
	this.Id = id
	this.Email = email
	this.Plan = plan
	this.Amount = amount
	this.ChurnDate = churnDate
	return &this
}

// NewChurnedUserWithDefaults instantiates a new ChurnedUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChurnedUserWithDefaults() *ChurnedUser {
	this := ChurnedUser{}
	return &this
}

// GetId returns the Id field value
func (o *ChurnedUser) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChurnedUser) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChurnedUser) SetId(v string) {
	o.Id = v
}

// GetEmail returns the Email field value
func (o *ChurnedUser) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ChurnedUser) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ChurnedUser) SetEmail(v string) {
	o.Email = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChurnedUser) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChurnedUser) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ChurnedUser) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ChurnedUser) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *ChurnedUser) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ChurnedUser) UnsetName() {
	o.Name.Unset()
}

// GetPlan returns the Plan field value
func (o *ChurnedUser) GetPlan() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *ChurnedUser) GetPlanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *ChurnedUser) SetPlan(v string) {
	o.Plan = v
}

// GetAmount returns the Amount field value
func (o *ChurnedUser) GetAmount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *ChurnedUser) GetAmountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *ChurnedUser) SetAmount(v float64) {
	o.Amount = v
}

// GetChurnDate returns the ChurnDate field value
func (o *ChurnedUser) GetChurnDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ChurnDate
}

// GetChurnDateOk returns a tuple with the ChurnDate field value
// and a boolean to check if the value has been set.
func (o *ChurnedUser) GetChurnDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChurnDate, true
}

// SetChurnDate sets field value
func (o *ChurnedUser) SetChurnDate(v time.Time) {
	o.ChurnDate = v
}

func (o ChurnedUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChurnedUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["email"] = o.Email
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	toSerialize["plan"] = o.Plan
	toSerialize["amount"] = o.Amount
	toSerialize["churn_date"] = o.ChurnDate
	return toSerialize, nil
}

func (o *ChurnedUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"email",
		"plan",
		"amount",
		"churn_date",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChurnedUser := _ChurnedUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChurnedUser)

	if err != nil {
		return err
	}

	*o = ChurnedUser(varChurnedUser)

	return err
}

type NullableChurnedUser struct {
	value *ChurnedUser
	isSet bool
}

func (v NullableChurnedUser) Get() *ChurnedUser {
	return v.value
}

func (v *NullableChurnedUser) Set(val *ChurnedUser) {
	v.value = val
	v.isSet = true
}

func (v NullableChurnedUser) IsSet() bool {
	return v.isSet
}

func (v *NullableChurnedUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChurnedUser(val *ChurnedUser) *NullableChurnedUser {
	return &NullableChurnedUser{value: val, isSet: true}
}

func (v NullableChurnedUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChurnedUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


