/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Enable2faResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Enable2faResponse{}

// Enable2faResponse TOTP secret and QR code URL returned after enabling 2FA
type Enable2faResponse struct {
	// TOTP secret key
	Secret string `json:"secret"`
	// QR code provisioning URL
	QrUrl string `json:"qr_url"`
}

type _Enable2faResponse Enable2faResponse

// NewEnable2faResponse instantiates a new Enable2faResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnable2faResponse(secret string, qrUrl string) *Enable2faResponse {
	this := Enable2faResponse{}
	this.Secret = secret
	this.QrUrl = qrUrl
	return &this
}

// NewEnable2faResponseWithDefaults instantiates a new Enable2faResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnable2faResponseWithDefaults() *Enable2faResponse {
	this := Enable2faResponse{}
	return &this
}

// GetSecret returns the Secret field value
func (o *Enable2faResponse) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *Enable2faResponse) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *Enable2faResponse) SetSecret(v string) {
	o.Secret = v
}

// GetQrUrl returns the QrUrl field value
func (o *Enable2faResponse) GetQrUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QrUrl
}

// GetQrUrlOk returns a tuple with the QrUrl field value
// and a boolean to check if the value has been set.
func (o *Enable2faResponse) GetQrUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QrUrl, true
}

// SetQrUrl sets field value
func (o *Enable2faResponse) SetQrUrl(v string) {
	o.QrUrl = v
}

func (o Enable2faResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Enable2faResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["secret"] = o.Secret
	toSerialize["qr_url"] = o.QrUrl
	return toSerialize, nil
}

func (o *Enable2faResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"secret",
		"qr_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnable2faResponse := _Enable2faResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnable2faResponse)

	if err != nil {
		return err
	}

	*o = Enable2faResponse(varEnable2faResponse)

	return err
}

type NullableEnable2faResponse struct {
	value *Enable2faResponse
	isSet bool
}

func (v NullableEnable2faResponse) Get() *Enable2faResponse {
	return v.value
}

func (v *NullableEnable2faResponse) Set(val *Enable2faResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEnable2faResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEnable2faResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnable2faResponse(val *Enable2faResponse) *NullableEnable2faResponse {
	return &NullableEnable2faResponse{value: val, isSet: true}
}

func (v NullableEnable2faResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnable2faResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


