/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the AuthConsentGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthConsentGet200Response{}

// AuthConsentGet200Response struct for AuthConsentGet200Response
type AuthConsentGet200Response struct {
	Consents *map[string]bool `json:"consents,omitempty"`
}

// NewAuthConsentGet200Response instantiates a new AuthConsentGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthConsentGet200Response() *AuthConsentGet200Response {
	this := AuthConsentGet200Response{}
	return &this
}

// NewAuthConsentGet200ResponseWithDefaults instantiates a new AuthConsentGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthConsentGet200ResponseWithDefaults() *AuthConsentGet200Response {
	this := AuthConsentGet200Response{}
	return &this
}

// GetConsents returns the Consents field value if set, zero value otherwise.
func (o *AuthConsentGet200Response) GetConsents() map[string]bool {
	if o == nil || IsNil(o.Consents) {
		var ret map[string]bool
		return ret
	}
	return *o.Consents
}

// GetConsentsOk returns a tuple with the Consents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConsentGet200Response) GetConsentsOk() (*map[string]bool, bool) {
	if o == nil || IsNil(o.Consents) {
		return nil, false
	}
	return o.Consents, true
}

// HasConsents returns a boolean if a field has been set.
func (o *AuthConsentGet200Response) HasConsents() bool {
	if o != nil && !IsNil(o.Consents) {
		return true
	}

	return false
}

// SetConsents gets a reference to the given map[string]bool and assigns it to the Consents field.
func (o *AuthConsentGet200Response) SetConsents(v map[string]bool) {
	o.Consents = &v
}

func (o AuthConsentGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthConsentGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Consents) {
		toSerialize["consents"] = o.Consents
	}
	return toSerialize, nil
}

type NullableAuthConsentGet200Response struct {
	value *AuthConsentGet200Response
	isSet bool
}

func (v NullableAuthConsentGet200Response) Get() *AuthConsentGet200Response {
	return v.value
}

func (v *NullableAuthConsentGet200Response) Set(val *AuthConsentGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthConsentGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthConsentGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthConsentGet200Response(val *AuthConsentGet200Response) *NullableAuthConsentGet200Response {
	return &NullableAuthConsentGet200Response{value: val, isSet: true}
}

func (v NullableAuthConsentGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthConsentGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


