/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateTransformRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTransformRuleRequest{}

// UpdateTransformRuleRequest Update an existing transform rule (all fields optional)
type UpdateTransformRuleRequest struct {
	Name string `json:"name"`
	// Updated transformation configuration
	Config map[string]interface{} `json:"config,omitempty"`
}

type _UpdateTransformRuleRequest UpdateTransformRuleRequest

// NewUpdateTransformRuleRequest instantiates a new UpdateTransformRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTransformRuleRequest(name string) *UpdateTransformRuleRequest {
	this := UpdateTransformRuleRequest{}
	this.Name = name
	return &this
}

// NewUpdateTransformRuleRequestWithDefaults instantiates a new UpdateTransformRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTransformRuleRequestWithDefaults() *UpdateTransformRuleRequest {
	this := UpdateTransformRuleRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateTransformRuleRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateTransformRuleRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateTransformRuleRequest) SetName(v string) {
	o.Name = v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *UpdateTransformRuleRequest) GetConfig() map[string]interface{} {
	if o == nil || IsNil(o.Config) {
		var ret map[string]interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTransformRuleRequest) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *UpdateTransformRuleRequest) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]interface{} and assigns it to the Config field.
func (o *UpdateTransformRuleRequest) SetConfig(v map[string]interface{}) {
	o.Config = v
}

func (o UpdateTransformRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTransformRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

func (o *UpdateTransformRuleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateTransformRuleRequest := _UpdateTransformRuleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateTransformRuleRequest)

	if err != nil {
		return err
	}

	*o = UpdateTransformRuleRequest(varUpdateTransformRuleRequest)

	return err
}

type NullableUpdateTransformRuleRequest struct {
	value *UpdateTransformRuleRequest
	isSet bool
}

func (v NullableUpdateTransformRuleRequest) Get() *UpdateTransformRuleRequest {
	return v.value
}

func (v *NullableUpdateTransformRuleRequest) Set(val *UpdateTransformRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTransformRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTransformRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTransformRuleRequest(val *UpdateTransformRuleRequest) *NullableUpdateTransformRuleRequest {
	return &NullableUpdateTransformRuleRequest{value: val, isSet: true}
}

func (v NullableUpdateTransformRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTransformRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


