/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the ApplicationsIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationsIdPutRequest{}

// ApplicationsIdPutRequest struct for ApplicationsIdPutRequest
type ApplicationsIdPutRequest struct {
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
}

// NewApplicationsIdPutRequest instantiates a new ApplicationsIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationsIdPutRequest() *ApplicationsIdPutRequest {
	this := ApplicationsIdPutRequest{}
	return &this
}

// NewApplicationsIdPutRequestWithDefaults instantiates a new ApplicationsIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationsIdPutRequestWithDefaults() *ApplicationsIdPutRequest {
	this := ApplicationsIdPutRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApplicationsIdPutRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationsIdPutRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApplicationsIdPutRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApplicationsIdPutRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApplicationsIdPutRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationsIdPutRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApplicationsIdPutRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApplicationsIdPutRequest) SetDescription(v string) {
	o.Description = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *ApplicationsIdPutRequest) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationsIdPutRequest) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *ApplicationsIdPutRequest) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *ApplicationsIdPutRequest) SetIsActive(v bool) {
	o.IsActive = &v
}

func (o ApplicationsIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationsIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	return toSerialize, nil
}

type NullableApplicationsIdPutRequest struct {
	value *ApplicationsIdPutRequest
	isSet bool
}

func (v NullableApplicationsIdPutRequest) Get() *ApplicationsIdPutRequest {
	return v.value
}

func (v *NullableApplicationsIdPutRequest) Set(val *ApplicationsIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationsIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationsIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationsIdPutRequest(val *ApplicationsIdPutRequest) *NullableApplicationsIdPutRequest {
	return &NullableApplicationsIdPutRequest{value: val, isSet: true}
}

func (v NullableApplicationsIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationsIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


