/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RevenueResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RevenueResponse{}

// RevenueResponse Full revenue analytics response
type RevenueResponse struct {
	MonthlyRevenue []RevenueResponseMonthlyRevenueInner `json:"monthly_revenue"`
	RevenueByPlan []RevenueResponseRevenueByPlanInner `json:"revenue_by_plan"`
	Mrr float64 `json:"mrr"`
	ChurnRate float64 `json:"churn_rate"`
	MrrTrend float64 `json:"mrr_trend"`
}

type _RevenueResponse RevenueResponse

// NewRevenueResponse instantiates a new RevenueResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRevenueResponse(monthlyRevenue []RevenueResponseMonthlyRevenueInner, revenueByPlan []RevenueResponseRevenueByPlanInner, mrr float64, churnRate float64, mrrTrend float64) *RevenueResponse {
	this := RevenueResponse{}
	this.MonthlyRevenue = monthlyRevenue
	this.RevenueByPlan = revenueByPlan
	this.Mrr = mrr
	this.ChurnRate = churnRate
	this.MrrTrend = mrrTrend
	return &this
}

// NewRevenueResponseWithDefaults instantiates a new RevenueResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRevenueResponseWithDefaults() *RevenueResponse {
	this := RevenueResponse{}
	return &this
}

// GetMonthlyRevenue returns the MonthlyRevenue field value
func (o *RevenueResponse) GetMonthlyRevenue() []RevenueResponseMonthlyRevenueInner {
	if o == nil {
		var ret []RevenueResponseMonthlyRevenueInner
		return ret
	}

	return o.MonthlyRevenue
}

// GetMonthlyRevenueOk returns a tuple with the MonthlyRevenue field value
// and a boolean to check if the value has been set.
func (o *RevenueResponse) GetMonthlyRevenueOk() ([]RevenueResponseMonthlyRevenueInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.MonthlyRevenue, true
}

// SetMonthlyRevenue sets field value
func (o *RevenueResponse) SetMonthlyRevenue(v []RevenueResponseMonthlyRevenueInner) {
	o.MonthlyRevenue = v
}

// GetRevenueByPlan returns the RevenueByPlan field value
func (o *RevenueResponse) GetRevenueByPlan() []RevenueResponseRevenueByPlanInner {
	if o == nil {
		var ret []RevenueResponseRevenueByPlanInner
		return ret
	}

	return o.RevenueByPlan
}

// GetRevenueByPlanOk returns a tuple with the RevenueByPlan field value
// and a boolean to check if the value has been set.
func (o *RevenueResponse) GetRevenueByPlanOk() ([]RevenueResponseRevenueByPlanInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.RevenueByPlan, true
}

// SetRevenueByPlan sets field value
func (o *RevenueResponse) SetRevenueByPlan(v []RevenueResponseRevenueByPlanInner) {
	o.RevenueByPlan = v
}

// GetMrr returns the Mrr field value
func (o *RevenueResponse) GetMrr() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Mrr
}

// GetMrrOk returns a tuple with the Mrr field value
// and a boolean to check if the value has been set.
func (o *RevenueResponse) GetMrrOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mrr, true
}

// SetMrr sets field value
func (o *RevenueResponse) SetMrr(v float64) {
	o.Mrr = v
}

// GetChurnRate returns the ChurnRate field value
func (o *RevenueResponse) GetChurnRate() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.ChurnRate
}

// GetChurnRateOk returns a tuple with the ChurnRate field value
// and a boolean to check if the value has been set.
func (o *RevenueResponse) GetChurnRateOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChurnRate, true
}

// SetChurnRate sets field value
func (o *RevenueResponse) SetChurnRate(v float64) {
	o.ChurnRate = v
}

// GetMrrTrend returns the MrrTrend field value
func (o *RevenueResponse) GetMrrTrend() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MrrTrend
}

// GetMrrTrendOk returns a tuple with the MrrTrend field value
// and a boolean to check if the value has been set.
func (o *RevenueResponse) GetMrrTrendOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MrrTrend, true
}

// SetMrrTrend sets field value
func (o *RevenueResponse) SetMrrTrend(v float64) {
	o.MrrTrend = v
}

func (o RevenueResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RevenueResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["monthly_revenue"] = o.MonthlyRevenue
	toSerialize["revenue_by_plan"] = o.RevenueByPlan
	toSerialize["mrr"] = o.Mrr
	toSerialize["churn_rate"] = o.ChurnRate
	toSerialize["mrr_trend"] = o.MrrTrend
	return toSerialize, nil
}

func (o *RevenueResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"monthly_revenue",
		"revenue_by_plan",
		"mrr",
		"churn_rate",
		"mrr_trend",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRevenueResponse := _RevenueResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRevenueResponse)

	if err != nil {
		return err
	}

	*o = RevenueResponse(varRevenueResponse)

	return err
}

type NullableRevenueResponse struct {
	value *RevenueResponse
	isSet bool
}

func (v NullableRevenueResponse) Get() *RevenueResponse {
	return v.value
}

func (v *NullableRevenueResponse) Set(val *RevenueResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRevenueResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRevenueResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRevenueResponse(val *RevenueResponse) *NullableRevenueResponse {
	return &NullableRevenueResponse{value: val, isSet: true}
}

func (v NullableRevenueResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRevenueResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


