/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSSOConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSSOConfigRequest{}

// CreateSSOConfigRequest Create a new SSO configuration
type CreateSSOConfigRequest struct {
	Provider string `json:"provider"`
	Domain string `json:"domain"`
	// URL to SAML metadata or OIDC discovery document
	MetadataUrl string `json:"metadata_url"`
}

type _CreateSSOConfigRequest CreateSSOConfigRequest

// NewCreateSSOConfigRequest instantiates a new CreateSSOConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSSOConfigRequest(provider string, domain string, metadataUrl string) *CreateSSOConfigRequest {
	this := CreateSSOConfigRequest{}
	this.Provider = provider
	this.Domain = domain
	this.MetadataUrl = metadataUrl
	return &this
}

// NewCreateSSOConfigRequestWithDefaults instantiates a new CreateSSOConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSSOConfigRequestWithDefaults() *CreateSSOConfigRequest {
	this := CreateSSOConfigRequest{}
	return &this
}

// GetProvider returns the Provider field value
func (o *CreateSSOConfigRequest) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *CreateSSOConfigRequest) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *CreateSSOConfigRequest) SetProvider(v string) {
	o.Provider = v
}

// GetDomain returns the Domain field value
func (o *CreateSSOConfigRequest) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *CreateSSOConfigRequest) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *CreateSSOConfigRequest) SetDomain(v string) {
	o.Domain = v
}

// GetMetadataUrl returns the MetadataUrl field value
func (o *CreateSSOConfigRequest) GetMetadataUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MetadataUrl
}

// GetMetadataUrlOk returns a tuple with the MetadataUrl field value
// and a boolean to check if the value has been set.
func (o *CreateSSOConfigRequest) GetMetadataUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetadataUrl, true
}

// SetMetadataUrl sets field value
func (o *CreateSSOConfigRequest) SetMetadataUrl(v string) {
	o.MetadataUrl = v
}

func (o CreateSSOConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSSOConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider"] = o.Provider
	toSerialize["domain"] = o.Domain
	toSerialize["metadata_url"] = o.MetadataUrl
	return toSerialize, nil
}

func (o *CreateSSOConfigRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider",
		"domain",
		"metadata_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSSOConfigRequest := _CreateSSOConfigRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSSOConfigRequest)

	if err != nil {
		return err
	}

	*o = CreateSSOConfigRequest(varCreateSSOConfigRequest)

	return err
}

type NullableCreateSSOConfigRequest struct {
	value *CreateSSOConfigRequest
	isSet bool
}

func (v NullableCreateSSOConfigRequest) Get() *CreateSSOConfigRequest {
	return v.value
}

func (v *NullableCreateSSOConfigRequest) Set(val *CreateSSOConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSSOConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSSOConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSSOConfigRequest(val *CreateSSOConfigRequest) *NullableCreateSSOConfigRequest {
	return &NullableCreateSSOConfigRequest{value: val, isSet: true}
}

func (v NullableCreateSSOConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSSOConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


