/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Delivery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Delivery{}

// Delivery struct for Delivery
type Delivery struct {
	Id string `json:"id"`
	EndpointId string `json:"endpoint_id"`
	Event NullableString `json:"event,omitempty"`
	Status string `json:"status"`
	AttemptCount int32 `json:"attempt_count"`
	ResponseStatus NullableInt32 `json:"response_status,omitempty"`
	ReplayCount int32 `json:"replay_count"`
	CreatedAt time.Time `json:"created_at"`
}

type _Delivery Delivery

// NewDelivery instantiates a new Delivery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDelivery(id string, endpointId string, status string, attemptCount int32, replayCount int32, createdAt time.Time) *Delivery {
	this := Delivery{}
	this.Id = id
	this.EndpointId = endpointId
	this.Status = status
	this.AttemptCount = attemptCount
	this.ReplayCount = replayCount
	this.CreatedAt = createdAt
	return &this
}

// NewDeliveryWithDefaults instantiates a new Delivery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryWithDefaults() *Delivery {
	this := Delivery{}
	return &this
}

// GetId returns the Id field value
func (o *Delivery) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Delivery) SetId(v string) {
	o.Id = v
}

// GetEndpointId returns the EndpointId field value
func (o *Delivery) GetEndpointId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetEndpointIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointId, true
}

// SetEndpointId sets field value
func (o *Delivery) SetEndpointId(v string) {
	o.EndpointId = v
}

// GetEvent returns the Event field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Delivery) GetEvent() string {
	if o == nil || IsNil(o.Event.Get()) {
		var ret string
		return ret
	}
	return *o.Event.Get()
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Delivery) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Event.Get(), o.Event.IsSet()
}

// HasEvent returns a boolean if a field has been set.
func (o *Delivery) HasEvent() bool {
	if o != nil && o.Event.IsSet() {
		return true
	}

	return false
}

// SetEvent gets a reference to the given NullableString and assigns it to the Event field.
func (o *Delivery) SetEvent(v string) {
	o.Event.Set(&v)
}
// SetEventNil sets the value for Event to be an explicit nil
func (o *Delivery) SetEventNil() {
	o.Event.Set(nil)
}

// UnsetEvent ensures that no value is present for Event, not even an explicit nil
func (o *Delivery) UnsetEvent() {
	o.Event.Unset()
}

// GetStatus returns the Status field value
func (o *Delivery) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Delivery) SetStatus(v string) {
	o.Status = v
}

// GetAttemptCount returns the AttemptCount field value
func (o *Delivery) GetAttemptCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AttemptCount
}

// GetAttemptCountOk returns a tuple with the AttemptCount field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetAttemptCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttemptCount, true
}

// SetAttemptCount sets field value
func (o *Delivery) SetAttemptCount(v int32) {
	o.AttemptCount = v
}

// GetResponseStatus returns the ResponseStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Delivery) GetResponseStatus() int32 {
	if o == nil || IsNil(o.ResponseStatus.Get()) {
		var ret int32
		return ret
	}
	return *o.ResponseStatus.Get()
}

// GetResponseStatusOk returns a tuple with the ResponseStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Delivery) GetResponseStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResponseStatus.Get(), o.ResponseStatus.IsSet()
}

// HasResponseStatus returns a boolean if a field has been set.
func (o *Delivery) HasResponseStatus() bool {
	if o != nil && o.ResponseStatus.IsSet() {
		return true
	}

	return false
}

// SetResponseStatus gets a reference to the given NullableInt32 and assigns it to the ResponseStatus field.
func (o *Delivery) SetResponseStatus(v int32) {
	o.ResponseStatus.Set(&v)
}
// SetResponseStatusNil sets the value for ResponseStatus to be an explicit nil
func (o *Delivery) SetResponseStatusNil() {
	o.ResponseStatus.Set(nil)
}

// UnsetResponseStatus ensures that no value is present for ResponseStatus, not even an explicit nil
func (o *Delivery) UnsetResponseStatus() {
	o.ResponseStatus.Unset()
}

// GetReplayCount returns the ReplayCount field value
func (o *Delivery) GetReplayCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReplayCount
}

// GetReplayCountOk returns a tuple with the ReplayCount field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetReplayCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReplayCount, true
}

// SetReplayCount sets field value
func (o *Delivery) SetReplayCount(v int32) {
	o.ReplayCount = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Delivery) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Delivery) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o Delivery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Delivery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["endpoint_id"] = o.EndpointId
	if o.Event.IsSet() {
		toSerialize["event"] = o.Event.Get()
	}
	toSerialize["status"] = o.Status
	toSerialize["attempt_count"] = o.AttemptCount
	if o.ResponseStatus.IsSet() {
		toSerialize["response_status"] = o.ResponseStatus.Get()
	}
	toSerialize["replay_count"] = o.ReplayCount
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *Delivery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"endpoint_id",
		"status",
		"attempt_count",
		"replay_count",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDelivery := _Delivery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDelivery)

	if err != nil {
		return err
	}

	*o = Delivery(varDelivery)

	return err
}

type NullableDelivery struct {
	value *Delivery
	isSet bool
}

func (v NullableDelivery) Get() *Delivery {
	return v.value
}

func (v *NullableDelivery) Set(val *Delivery) {
	v.value = val
	v.isSet = true
}

func (v NullableDelivery) IsSet() bool {
	return v.isSet
}

func (v *NullableDelivery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDelivery(val *Delivery) *NullableDelivery {
	return &NullableDelivery{value: val, isSet: true}
}

func (v NullableDelivery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDelivery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


