/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StatsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsResponse{}

// StatsResponse struct for StatsResponse
type StatsResponse struct {
	TotalDeliveries int32 `json:"total_deliveries"`
	SuccessfulDeliveries int32 `json:"successful_deliveries"`
	FailedDeliveries int32 `json:"failed_deliveries"`
	TotalEndpoints int32 `json:"total_endpoints"`
	ActiveEndpoints int32 `json:"active_endpoints"`
	Plan string `json:"plan"`
	WebhookLimit int32 `json:"webhook_limit"`
	WebhookCount int32 `json:"webhook_count"`
}

type _StatsResponse StatsResponse

// NewStatsResponse instantiates a new StatsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsResponse(totalDeliveries int32, successfulDeliveries int32, failedDeliveries int32, totalEndpoints int32, activeEndpoints int32, plan string, webhookLimit int32, webhookCount int32) *StatsResponse {
	this := StatsResponse{}
	this.TotalDeliveries = totalDeliveries
	this.SuccessfulDeliveries = successfulDeliveries
	this.FailedDeliveries = failedDeliveries
	this.TotalEndpoints = totalEndpoints
	this.ActiveEndpoints = activeEndpoints
	this.Plan = plan
	this.WebhookLimit = webhookLimit
	this.WebhookCount = webhookCount
	return &this
}

// NewStatsResponseWithDefaults instantiates a new StatsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsResponseWithDefaults() *StatsResponse {
	this := StatsResponse{}
	return &this
}

// GetTotalDeliveries returns the TotalDeliveries field value
func (o *StatsResponse) GetTotalDeliveries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalDeliveries
}

// GetTotalDeliveriesOk returns a tuple with the TotalDeliveries field value
// and a boolean to check if the value has been set.
func (o *StatsResponse) GetTotalDeliveriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalDeliveries, true
}

// SetTotalDeliveries sets field value
func (o *StatsResponse) SetTotalDeliveries(v int32) {
	o.TotalDeliveries = v
}

// GetSuccessfulDeliveries returns the SuccessfulDeliveries field value
func (o *StatsResponse) GetSuccessfulDeliveries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SuccessfulDeliveries
}

// GetSuccessfulDeliveriesOk returns a tuple with the SuccessfulDeliveries field value
// and a boolean to check if the value has been set.
func (o *StatsResponse) GetSuccessfulDeliveriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuccessfulDeliveries, true
}

// SetSuccessfulDeliveries sets field value
func (o *StatsResponse) SetSuccessfulDeliveries(v int32) {
	o.SuccessfulDeliveries = v
}

// GetFailedDeliveries returns the FailedDeliveries field value
func (o *StatsResponse) GetFailedDeliveries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FailedDeliveries
}

// GetFailedDeliveriesOk returns a tuple with the FailedDeliveries field value
// and a boolean to check if the value has been set.
func (o *StatsResponse) GetFailedDeliveriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailedDeliveries, true
}

// SetFailedDeliveries sets field value
func (o *StatsResponse) SetFailedDeliveries(v int32) {
	o.FailedDeliveries = v
}

// GetTotalEndpoints returns the TotalEndpoints field value
func (o *StatsResponse) GetTotalEndpoints() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalEndpoints
}

// GetTotalEndpointsOk returns a tuple with the TotalEndpoints field value
// and a boolean to check if the value has been set.
func (o *StatsResponse) GetTotalEndpointsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalEndpoints, true
}

// SetTotalEndpoints sets field value
func (o *StatsResponse) SetTotalEndpoints(v int32) {
	o.TotalEndpoints = v
}

// GetActiveEndpoints returns the ActiveEndpoints field value
func (o *StatsResponse) GetActiveEndpoints() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActiveEndpoints
}

// GetActiveEndpointsOk returns a tuple with the ActiveEndpoints field value
// and a boolean to check if the value has been set.
func (o *StatsResponse) GetActiveEndpointsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveEndpoints, true
}

// SetActiveEndpoints sets field value
func (o *StatsResponse) SetActiveEndpoints(v int32) {
	o.ActiveEndpoints = v
}

// GetPlan returns the Plan field value
func (o *StatsResponse) GetPlan() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *StatsResponse) GetPlanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *StatsResponse) SetPlan(v string) {
	o.Plan = v
}

// GetWebhookLimit returns the WebhookLimit field value
func (o *StatsResponse) GetWebhookLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WebhookLimit
}

// GetWebhookLimitOk returns a tuple with the WebhookLimit field value
// and a boolean to check if the value has been set.
func (o *StatsResponse) GetWebhookLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebhookLimit, true
}

// SetWebhookLimit sets field value
func (o *StatsResponse) SetWebhookLimit(v int32) {
	o.WebhookLimit = v
}

// GetWebhookCount returns the WebhookCount field value
func (o *StatsResponse) GetWebhookCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WebhookCount
}

// GetWebhookCountOk returns a tuple with the WebhookCount field value
// and a boolean to check if the value has been set.
func (o *StatsResponse) GetWebhookCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebhookCount, true
}

// SetWebhookCount sets field value
func (o *StatsResponse) SetWebhookCount(v int32) {
	o.WebhookCount = v
}

func (o StatsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total_deliveries"] = o.TotalDeliveries
	toSerialize["successful_deliveries"] = o.SuccessfulDeliveries
	toSerialize["failed_deliveries"] = o.FailedDeliveries
	toSerialize["total_endpoints"] = o.TotalEndpoints
	toSerialize["active_endpoints"] = o.ActiveEndpoints
	toSerialize["plan"] = o.Plan
	toSerialize["webhook_limit"] = o.WebhookLimit
	toSerialize["webhook_count"] = o.WebhookCount
	return toSerialize, nil
}

func (o *StatsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total_deliveries",
		"successful_deliveries",
		"failed_deliveries",
		"total_endpoints",
		"active_endpoints",
		"plan",
		"webhook_limit",
		"webhook_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatsResponse := _StatsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStatsResponse)

	if err != nil {
		return err
	}

	*o = StatsResponse(varStatsResponse)

	return err
}

type NullableStatsResponse struct {
	value *StatsResponse
	isSet bool
}

func (v NullableStatsResponse) Get() *StatsResponse {
	return v.value
}

func (v *NullableStatsResponse) Set(val *StatsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsResponse(val *StatsResponse) *NullableStatsResponse {
	return &NullableStatsResponse{value: val, isSet: true}
}

func (v NullableStatsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


