/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeviceListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceListResponse{}

// DeviceListResponse Paginated list of registered devices
type DeviceListResponse struct {
	Data []DeviceTokenResponse `json:"data"`
}

type _DeviceListResponse DeviceListResponse

// NewDeviceListResponse instantiates a new DeviceListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceListResponse(data []DeviceTokenResponse) *DeviceListResponse {
	this := DeviceListResponse{}
	this.Data = data
	return &this
}

// NewDeviceListResponseWithDefaults instantiates a new DeviceListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceListResponseWithDefaults() *DeviceListResponse {
	this := DeviceListResponse{}
	return &this
}

// GetData returns the Data field value
func (o *DeviceListResponse) GetData() []DeviceTokenResponse {
	if o == nil {
		var ret []DeviceTokenResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeviceListResponse) GetDataOk() ([]DeviceTokenResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *DeviceListResponse) SetData(v []DeviceTokenResponse) {
	o.Data = v
}

func (o DeviceListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeviceListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceListResponse := _DeviceListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceListResponse)

	if err != nil {
		return err
	}

	*o = DeviceListResponse(varDeviceListResponse)

	return err
}

type NullableDeviceListResponse struct {
	value *DeviceListResponse
	isSet bool
}

func (v NullableDeviceListResponse) Get() *DeviceListResponse {
	return v.value
}

func (v *NullableDeviceListResponse) Set(val *DeviceListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceListResponse(val *DeviceListResponse) *NullableDeviceListResponse {
	return &NullableDeviceListResponse{value: val, isSet: true}
}

func (v NullableDeviceListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


