/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the RevenueResponseMonthlyRevenueInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RevenueResponseMonthlyRevenueInner{}

// RevenueResponseMonthlyRevenueInner struct for RevenueResponseMonthlyRevenueInner
type RevenueResponseMonthlyRevenueInner struct {
	Month *string `json:"month,omitempty"`
	Revenue *float64 `json:"revenue,omitempty"`
}

// NewRevenueResponseMonthlyRevenueInner instantiates a new RevenueResponseMonthlyRevenueInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRevenueResponseMonthlyRevenueInner() *RevenueResponseMonthlyRevenueInner {
	this := RevenueResponseMonthlyRevenueInner{}
	return &this
}

// NewRevenueResponseMonthlyRevenueInnerWithDefaults instantiates a new RevenueResponseMonthlyRevenueInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRevenueResponseMonthlyRevenueInnerWithDefaults() *RevenueResponseMonthlyRevenueInner {
	this := RevenueResponseMonthlyRevenueInner{}
	return &this
}

// GetMonth returns the Month field value if set, zero value otherwise.
func (o *RevenueResponseMonthlyRevenueInner) GetMonth() string {
	if o == nil || IsNil(o.Month) {
		var ret string
		return ret
	}
	return *o.Month
}

// GetMonthOk returns a tuple with the Month field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevenueResponseMonthlyRevenueInner) GetMonthOk() (*string, bool) {
	if o == nil || IsNil(o.Month) {
		return nil, false
	}
	return o.Month, true
}

// HasMonth returns a boolean if a field has been set.
func (o *RevenueResponseMonthlyRevenueInner) HasMonth() bool {
	if o != nil && !IsNil(o.Month) {
		return true
	}

	return false
}

// SetMonth gets a reference to the given string and assigns it to the Month field.
func (o *RevenueResponseMonthlyRevenueInner) SetMonth(v string) {
	o.Month = &v
}

// GetRevenue returns the Revenue field value if set, zero value otherwise.
func (o *RevenueResponseMonthlyRevenueInner) GetRevenue() float64 {
	if o == nil || IsNil(o.Revenue) {
		var ret float64
		return ret
	}
	return *o.Revenue
}

// GetRevenueOk returns a tuple with the Revenue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevenueResponseMonthlyRevenueInner) GetRevenueOk() (*float64, bool) {
	if o == nil || IsNil(o.Revenue) {
		return nil, false
	}
	return o.Revenue, true
}

// HasRevenue returns a boolean if a field has been set.
func (o *RevenueResponseMonthlyRevenueInner) HasRevenue() bool {
	if o != nil && !IsNil(o.Revenue) {
		return true
	}

	return false
}

// SetRevenue gets a reference to the given float64 and assigns it to the Revenue field.
func (o *RevenueResponseMonthlyRevenueInner) SetRevenue(v float64) {
	o.Revenue = &v
}

func (o RevenueResponseMonthlyRevenueInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RevenueResponseMonthlyRevenueInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Month) {
		toSerialize["month"] = o.Month
	}
	if !IsNil(o.Revenue) {
		toSerialize["revenue"] = o.Revenue
	}
	return toSerialize, nil
}

type NullableRevenueResponseMonthlyRevenueInner struct {
	value *RevenueResponseMonthlyRevenueInner
	isSet bool
}

func (v NullableRevenueResponseMonthlyRevenueInner) Get() *RevenueResponseMonthlyRevenueInner {
	return v.value
}

func (v *NullableRevenueResponseMonthlyRevenueInner) Set(val *RevenueResponseMonthlyRevenueInner) {
	v.value = val
	v.isSet = true
}

func (v NullableRevenueResponseMonthlyRevenueInner) IsSet() bool {
	return v.isSet
}

func (v *NullableRevenueResponseMonthlyRevenueInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRevenueResponseMonthlyRevenueInner(val *RevenueResponseMonthlyRevenueInner) *NullableRevenueResponseMonthlyRevenueInner {
	return &NullableRevenueResponseMonthlyRevenueInner{value: val, isSet: true}
}

func (v NullableRevenueResponseMonthlyRevenueInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRevenueResponseMonthlyRevenueInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


