/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SystemStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemStats{}

// SystemStats struct for SystemStats
type SystemStats struct {
	TotalUsers int32 `json:"total_users"`
	ActiveUsers int32 `json:"active_users"`
	TotalEndpoints int32 `json:"total_endpoints"`
	TotalDeliveries int32 `json:"total_deliveries"`
	PlanBreakdown []SystemStatsPlanBreakdownInner `json:"plan_breakdown"`
}

type _SystemStats SystemStats

// NewSystemStats instantiates a new SystemStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemStats(totalUsers int32, activeUsers int32, totalEndpoints int32, totalDeliveries int32, planBreakdown []SystemStatsPlanBreakdownInner) *SystemStats {
	this := SystemStats{}
	this.TotalUsers = totalUsers
	this.ActiveUsers = activeUsers
	this.TotalEndpoints = totalEndpoints
	this.TotalDeliveries = totalDeliveries
	this.PlanBreakdown = planBreakdown
	return &this
}

// NewSystemStatsWithDefaults instantiates a new SystemStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemStatsWithDefaults() *SystemStats {
	this := SystemStats{}
	return &this
}

// GetTotalUsers returns the TotalUsers field value
func (o *SystemStats) GetTotalUsers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalUsers
}

// GetTotalUsersOk returns a tuple with the TotalUsers field value
// and a boolean to check if the value has been set.
func (o *SystemStats) GetTotalUsersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalUsers, true
}

// SetTotalUsers sets field value
func (o *SystemStats) SetTotalUsers(v int32) {
	o.TotalUsers = v
}

// GetActiveUsers returns the ActiveUsers field value
func (o *SystemStats) GetActiveUsers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActiveUsers
}

// GetActiveUsersOk returns a tuple with the ActiveUsers field value
// and a boolean to check if the value has been set.
func (o *SystemStats) GetActiveUsersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveUsers, true
}

// SetActiveUsers sets field value
func (o *SystemStats) SetActiveUsers(v int32) {
	o.ActiveUsers = v
}

// GetTotalEndpoints returns the TotalEndpoints field value
func (o *SystemStats) GetTotalEndpoints() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalEndpoints
}

// GetTotalEndpointsOk returns a tuple with the TotalEndpoints field value
// and a boolean to check if the value has been set.
func (o *SystemStats) GetTotalEndpointsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalEndpoints, true
}

// SetTotalEndpoints sets field value
func (o *SystemStats) SetTotalEndpoints(v int32) {
	o.TotalEndpoints = v
}

// GetTotalDeliveries returns the TotalDeliveries field value
func (o *SystemStats) GetTotalDeliveries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalDeliveries
}

// GetTotalDeliveriesOk returns a tuple with the TotalDeliveries field value
// and a boolean to check if the value has been set.
func (o *SystemStats) GetTotalDeliveriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalDeliveries, true
}

// SetTotalDeliveries sets field value
func (o *SystemStats) SetTotalDeliveries(v int32) {
	o.TotalDeliveries = v
}

// GetPlanBreakdown returns the PlanBreakdown field value
func (o *SystemStats) GetPlanBreakdown() []SystemStatsPlanBreakdownInner {
	if o == nil {
		var ret []SystemStatsPlanBreakdownInner
		return ret
	}

	return o.PlanBreakdown
}

// GetPlanBreakdownOk returns a tuple with the PlanBreakdown field value
// and a boolean to check if the value has been set.
func (o *SystemStats) GetPlanBreakdownOk() ([]SystemStatsPlanBreakdownInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlanBreakdown, true
}

// SetPlanBreakdown sets field value
func (o *SystemStats) SetPlanBreakdown(v []SystemStatsPlanBreakdownInner) {
	o.PlanBreakdown = v
}

func (o SystemStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total_users"] = o.TotalUsers
	toSerialize["active_users"] = o.ActiveUsers
	toSerialize["total_endpoints"] = o.TotalEndpoints
	toSerialize["total_deliveries"] = o.TotalDeliveries
	toSerialize["plan_breakdown"] = o.PlanBreakdown
	return toSerialize, nil
}

func (o *SystemStats) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total_users",
		"active_users",
		"total_endpoints",
		"total_deliveries",
		"plan_breakdown",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemStats := _SystemStats{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemStats)

	if err != nil {
		return err
	}

	*o = SystemStats(varSystemStats)

	return err
}

type NullableSystemStats struct {
	value *SystemStats
	isSet bool
}

func (v NullableSystemStats) Get() *SystemStats {
	return v.value
}

func (v *NullableSystemStats) Set(val *SystemStats) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemStats) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemStats(val *SystemStats) *NullableSystemStats {
	return &NullableSystemStats{value: val, isSet: true}
}

func (v NullableSystemStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


