/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TeamListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamListResponse{}

// TeamListResponse Paginated list of teams
type TeamListResponse struct {
	Data []Team `json:"data"`
	HasMore bool `json:"has_more"`
	Total int32 `json:"total"`
}

type _TeamListResponse TeamListResponse

// NewTeamListResponse instantiates a new TeamListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamListResponse(data []Team, hasMore bool, total int32) *TeamListResponse {
	this := TeamListResponse{}
	this.Data = data
	this.HasMore = hasMore
	this.Total = total
	return &this
}

// NewTeamListResponseWithDefaults instantiates a new TeamListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamListResponseWithDefaults() *TeamListResponse {
	this := TeamListResponse{}
	return &this
}

// GetData returns the Data field value
func (o *TeamListResponse) GetData() []Team {
	if o == nil {
		var ret []Team
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TeamListResponse) GetDataOk() ([]Team, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *TeamListResponse) SetData(v []Team) {
	o.Data = v
}

// GetHasMore returns the HasMore field value
func (o *TeamListResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *TeamListResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *TeamListResponse) SetHasMore(v bool) {
	o.HasMore = v
}

// GetTotal returns the Total field value
func (o *TeamListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *TeamListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *TeamListResponse) SetTotal(v int32) {
	o.Total = v
}

func (o TeamListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["has_more"] = o.HasMore
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *TeamListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"has_more",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTeamListResponse := _TeamListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTeamListResponse)

	if err != nil {
		return err
	}

	*o = TeamListResponse(varTeamListResponse)

	return err
}

type NullableTeamListResponse struct {
	value *TeamListResponse
	isSet bool
}

func (v NullableTeamListResponse) Get() *TeamListResponse {
	return v.value
}

func (v *NullableTeamListResponse) Set(val *TeamListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamListResponse(val *TeamListResponse) *NullableTeamListResponse {
	return &NullableTeamListResponse{value: val, isSet: true}
}

func (v NullableTeamListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


