/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OAuthLoginRedirect type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OAuthLoginRedirect{}

// OAuthLoginRedirect OAuth redirect information
type OAuthLoginRedirect struct {
	RedirectUrl string `json:"redirect_url"`
}

type _OAuthLoginRedirect OAuthLoginRedirect

// NewOAuthLoginRedirect instantiates a new OAuthLoginRedirect object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuthLoginRedirect(redirectUrl string) *OAuthLoginRedirect {
	this := OAuthLoginRedirect{}
	this.RedirectUrl = redirectUrl
	return &this
}

// NewOAuthLoginRedirectWithDefaults instantiates a new OAuthLoginRedirect object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuthLoginRedirectWithDefaults() *OAuthLoginRedirect {
	this := OAuthLoginRedirect{}
	return &this
}

// GetRedirectUrl returns the RedirectUrl field value
func (o *OAuthLoginRedirect) GetRedirectUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RedirectUrl
}

// GetRedirectUrlOk returns a tuple with the RedirectUrl field value
// and a boolean to check if the value has been set.
func (o *OAuthLoginRedirect) GetRedirectUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RedirectUrl, true
}

// SetRedirectUrl sets field value
func (o *OAuthLoginRedirect) SetRedirectUrl(v string) {
	o.RedirectUrl = v
}

func (o OAuthLoginRedirect) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OAuthLoginRedirect) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["redirect_url"] = o.RedirectUrl
	return toSerialize, nil
}

func (o *OAuthLoginRedirect) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"redirect_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOAuthLoginRedirect := _OAuthLoginRedirect{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOAuthLoginRedirect)

	if err != nil {
		return err
	}

	*o = OAuthLoginRedirect(varOAuthLoginRedirect)

	return err
}

type NullableOAuthLoginRedirect struct {
	value *OAuthLoginRedirect
	isSet bool
}

func (v NullableOAuthLoginRedirect) Get() *OAuthLoginRedirect {
	return v.value
}

func (v *NullableOAuthLoginRedirect) Set(val *OAuthLoginRedirect) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuthLoginRedirect) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuthLoginRedirect) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuthLoginRedirect(val *OAuthLoginRedirect) *NullableOAuthLoginRedirect {
	return &NullableOAuthLoginRedirect{value: val, isSet: true}
}

func (v NullableOAuthLoginRedirect) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuthLoginRedirect) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


