// ToJSON/FromJSON convenience methods for key generated model structs.
// These delegate to the existing ToMap()/UnmarshalJSON generated by OpenAPI Generator.

package hooksniff

import (
	"encoding/json"
)

// --- Endpoint ---

// ToJSON serializes Endpoint to a map for manual JSON construction.
func (o *Endpoint) ToJSON() map[string]interface{} {
	m, _ := o.ToMap()
	return m
}

// EndpointFromJSON constructs an Endpoint from a generic map (e.g. from json.Unmarshal).
func EndpointFromJSON(data map[string]interface{}) *Endpoint {
	e := &Endpoint{}
	if v, ok := data["id"].(string); ok {
		e.Id = v
	}
	if v, ok := data["url"].(string); ok {
		e.Url = v
	}
	if v, ok := data["description"].(string); ok {
		e.Description.Set(&v)
	}
	if v, ok := data["is_active"].(bool); ok {
		e.IsActive = v
	}
	if v, ok := data["retry_policy"].(map[string]interface{}); ok {
		e.RetryPolicy = *RetryPolicyFromJSON(v)
	}
	if v, ok := data["created_at"].(string); ok {
		e.CreatedAt = TimeFromJSON(v)
	}
	if v, ok := data["allowed_ips"].([]interface{}); ok {
		ips := make([]string, 0, len(v))
		for _, item := range v {
			if s, ok := item.(string); ok {
				ips = append(ips, s)
			}
		}
		e.AllowedIps = ips
	}
	if v, ok := data["event_filter"].([]interface{}); ok {
		filters := make([]string, 0, len(v))
		for _, item := range v {
			if s, ok := item.(string); ok {
				filters = append(filters, s)
			}
		}
		e.EventFilter = filters
	}
	if v, ok := data["custom_headers"].(map[string]interface{}); ok {
		e.CustomHeaders = v
	}
	if v, ok := data["routing_strategy"].(string); ok {
		e.RoutingStrategy = v
	}
	if v, ok := data["fallback_url"].(string); ok {
		e.FallbackUrl.Set(&v)
	}
	if v, ok := data["avg_response_ms"]; ok {
		e.AvgResponseMs = int32(toInt(v))
	}
	if v, ok := data["failure_streak"]; ok {
		e.FailureStreak = int32(toInt(v))
	}
	if v, ok := data["format"].(string); ok {
		e.Format = v
	}
	return e
}

// --- Delivery ---

func (o *Delivery) ToJSON() map[string]interface{} {
	m, _ := o.ToMap()
	return m
}

func DeliveryFromJSON(data map[string]interface{}) *Delivery {
	d := &Delivery{}
	if v, ok := data["id"].(string); ok {
		d.Id = v
	}
	if v, ok := data["endpoint_id"].(string); ok {
		d.EndpointId = v
	}
	if v, ok := data["event"].(string); ok {
		d.Event.Set(&v)
	}
	if v, ok := data["status"].(string); ok {
		d.Status = v
	}
	if v, ok := data["attempt_count"]; ok {
		d.AttemptCount = int32(toInt(v))
	}
	if v, ok := data["response_status"]; ok {
		val := int32(toInt(v))
		d.ResponseStatus.Set(&val)
	}
	if v, ok := data["replay_count"]; ok {
		d.ReplayCount = int32(toInt(v))
	}
	if v, ok := data["created_at"].(string); ok {
		d.CreatedAt = TimeFromJSON(v)
	}
	return d
}

// --- Error ---

func (o *Error) ToJSON() map[string]interface{} {
	m, _ := o.ToMap()
	return m
}

func ErrorFromJSON(data map[string]interface{}) *Error {
	e := &Error{}
	if v, ok := data["error"].(string); ok {
		e.Error = v
	}
	return e
}

// --- RetryPolicy ---

func (o *RetryPolicy) ToJSON() map[string]interface{} {
	m, _ := o.ToMap()
	return m
}

func RetryPolicyFromJSON(data map[string]interface{}) *RetryPolicy {
	r := &RetryPolicy{}
	if v, ok := data["max_attempts"]; ok {
		r.MaxAttempts = int32(toInt(v))
	}
	if v, ok := data["backoff"].(string); ok {
		r.Backoff = v
	}
	if v, ok := data["initial_delay_secs"]; ok {
		r.InitialDelaySecs = int32(toInt(v))
	}
	if v, ok := data["max_delay_secs"]; ok {
		r.MaxDelaySecs = int32(toInt(v))
	}
	return r
}

// --- AlertRule ---

func (o *AlertRule) ToJSON() map[string]interface{} {
	m, _ := o.ToMap()
	return m
}

func AlertRuleFromJSON(data map[string]interface{}) *AlertRule {
	a := &AlertRule{}
	if v, ok := data["id"].(string); ok {
		a.Id = v
	}
	if v, ok := data["name"].(string); ok {
		a.Name = v
	}
	if v, ok := data["condition"].(string); ok {
		a.Condition = v
	}
	if v, ok := data["threshold"]; ok {
		a.Threshold = int32(toInt(v))
	}
	if v, ok := data["channels"].([]interface{}); ok {
		channels := make([]string, 0, len(v))
		for _, ch := range v {
			if s, ok := ch.(string); ok {
				channels = append(channels, s)
			}
		}
		a.Channels = channels
	}
	if v, ok := data["is_active"].(bool); ok {
		a.IsActive = v
	}
	if v, ok := data["created_at"].(string); ok {
		a.CreatedAt = TimeFromJSON(v)
	}
	return a
}

// --- EventType ---

func (o *EventType) ToJSON() map[string]interface{} {
	m, _ := o.ToMap()
	return m
}

func EventTypeFromJSON(data map[string]interface{}) *EventType {
	e := &EventType{}
	if v, ok := data["id"].(string); ok {
		e.Id = v
	}
	if v, ok := data["name"].(string); ok {
		e.Name = v
	}
	if v, ok := data["description"].(string); ok {
		e.Description.Set(&v)
	}
	if v, ok := data["schema_id"].(string); ok {
		e.SchemaId = &v
	}
	return e
}

// --- CustomDomain ---

func (o *CustomDomain) ToJSON() map[string]interface{} {
	m, _ := o.ToMap()
	return m
}

func CustomDomainFromJSON(data map[string]interface{}) *CustomDomain {
	c := &CustomDomain{}
	if v, ok := data["id"].(string); ok {
		c.Id = v
	}
	if v, ok := data["domain"].(string); ok {
		c.Domain = v
	}
	if v, ok := data["status"].(string); ok {
		c.Status = v
	}
	if v, ok := data["verification_token"].(string); ok {
		c.VerificationToken.Set(&v)
	}
	if v, ok := data["created_at"].(string); ok {
		c.CreatedAt = TimeFromJSON(v)
	}
	return c
}

// --- TransformRule ---

func (o *TransformRule) ToJSON() map[string]interface{} {
	m, _ := o.ToMap()
	return m
}

func TransformRuleFromJSON(data map[string]interface{}) *TransformRule {
	t := &TransformRule{}
	if v, ok := data["id"].(string); ok {
		t.Id = v
	}
	if v, ok := data["endpoint_id"].(string); ok {
		t.EndpointId = v
	}
	if v, ok := data["name"].(string); ok {
		t.Name = v
	}
	if v, ok := data["rule_type"].(string); ok {
		t.RuleType = v
	}
	if v, ok := data["config"].(map[string]interface{}); ok {
		t.Config = v
	}
	if v, ok := data["is_active"].(bool); ok {
		t.IsActive = v
	}
	if v, ok := data["created_at"].(string); ok {
		t.CreatedAt = TimeFromJSON(v)
	}
	return t
}

// --- EndpointHealth ---

func (o *EndpointHealth) ToJSON() map[string]interface{} {
	m, _ := o.ToMap()
	return m
}

func EndpointHealthFromJSON(data map[string]interface{}) *EndpointHealth {
	e := &EndpointHealth{}
	if v, ok := data["endpoint_id"].(string); ok {
		e.EndpointId = v
	}
	if v, ok := data["is_healthy"].(bool); ok {
		e.IsHealthy = v
	}
	if v, ok := data["failure_streak"]; ok {
		val := int32(toInt(v))
		e.FailureStreak = &val
	}
	if v, ok := data["avg_response_ms"]; ok {
		val := int32(toInt(v))
		e.AvgResponseMs = &val
	}
	if v, ok := data["success_rate"]; ok {
		val := toFloat64(v)
		e.SuccessRate = &val
	}
	if v, ok := data["avg_latency_ms"]; ok {
		val := toFloat32(v)
		e.AvgLatencyMs = &val
	}
	if v, ok := data["total_deliveries"]; ok {
		val := int32(toInt(v))
		e.TotalDeliveries = &val
	}
	if v, ok := data["failed_deliveries"]; ok {
		val := int32(toInt(v))
		e.FailedDeliveries = &val
	}
	return e
}

// --- EndpointListResponse ---

func (o *EndpointListResponse) ToJSON() map[string]interface{} {
	m, _ := o.ToMap()
	return m
}

func EndpointListResponseFromJSON(data map[string]interface{}) *EndpointListResponse {
	e := &EndpointListResponse{}
	if v, ok := data["data"].([]interface{}); ok {
		endpoints := make([]Endpoint, 0, len(v))
		for _, item := range v {
			if itemMap, ok := item.(map[string]interface{}); ok {
				endpoints = append(endpoints, *EndpointFromJSON(itemMap))
			}
		}
		e.Data = endpoints
	}
	if v, ok := data["total"]; ok {
		e.Total = int32(toInt(v))
	}
	if v, ok := data["has_more"].(bool); ok {
		e.HasMore = v
	}
	return e
}

// --- DeliveryListResponse ---

func (o *DeliveryListResponse) ToJSON() map[string]interface{} {
	m, _ := o.ToMap()
	return m
}

func DeliveryListResponseFromJSON(data map[string]interface{}) *DeliveryListResponse {
	d := &DeliveryListResponse{}
	if v, ok := data["deliveries"].([]interface{}); ok {
		items := make([]Delivery, 0, len(v))
		for _, item := range v {
			if itemMap, ok := item.(map[string]interface{}); ok {
				items = append(items, *DeliveryFromJSON(itemMap))
			}
		}
		d.Deliveries = items
	}
	if v, ok := data["total"]; ok {
		d.Total = int32(toInt(v))
	}
	if v, ok := data["page"]; ok {
		d.Page = int32(toInt(v))
	}
	if v, ok := data["per_page"]; ok {
		d.PerPage = int32(toInt(v))
	}
	return d
}

// --- JSON roundtrip helper ---

// ToJSONBytes marshals any struct to indented JSON bytes.
func ToJSONBytes(v interface{}) ([]byte, error) {
	return json.MarshalIndent(v, "", "  ")
}

func toFloat64(v interface{}) float64 {
	switch n := v.(type) {
	case float64:
		return n
	case float32:
		return float64(n)
	case int:
		return float64(n)
	case int32:
		return float64(n)
	case int64:
		return float64(n)
	case json.Number:
		f, _ := n.Float64()
		return f
	default:
		return 0
	}
}

func toFloat32(v interface{}) float32 {
	switch n := v.(type) {
	case float64:
		return float32(n)
	case float32:
		return n
	case int:
		return float32(n)
	case int32:
		return float32(n)
	case int64:
		return float32(n)
	case json.Number:
		f, _ := n.Float64()
		return float32(f)
	default:
		return 0
	}
}
