// <auto-generated>
/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using hooksniff.Client;

namespace hooksniff.Model
{
    /// <summary>
    /// SuccessRateResponse
    /// </summary>
    public partial class SuccessRateResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SuccessRateResponse" /> class.
        /// </summary>
        /// <param name="range">range</param>
        /// <param name="successful">successful</param>
        /// <param name="failed">failed</param>
        /// <param name="pending">pending</param>
        /// <param name="successRate">successRate</param>
        [JsonConstructor]
        public SuccessRateResponse(Option<string?> range = default, Option<int?> successful = default, Option<int?> failed = default, Option<int?> pending = default, Option<double?> successRate = default)
        {
            RangeOption = range;
            SuccessfulOption = successful;
            FailedOption = failed;
            PendingOption = pending;
            SuccessRateOption = successRate;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Range
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RangeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Range
        /// </summary>
        [JsonPropertyName("range")]
        public string? Range { get { return this.RangeOption.Value; } set { this.RangeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Successful
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SuccessfulOption { get; private set; }

        /// <summary>
        /// Gets or Sets Successful
        /// </summary>
        [JsonPropertyName("successful")]
        public int? Successful { get { return this.SuccessfulOption.Value; } set { this.SuccessfulOption = new(value); } }

        /// <summary>
        /// Used to track the state of Failed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FailedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Failed
        /// </summary>
        [JsonPropertyName("failed")]
        public int? Failed { get { return this.FailedOption.Value; } set { this.FailedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Pending
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PendingOption { get; private set; }

        /// <summary>
        /// Gets or Sets Pending
        /// </summary>
        [JsonPropertyName("pending")]
        public int? Pending { get { return this.PendingOption.Value; } set { this.PendingOption = new(value); } }

        /// <summary>
        /// Used to track the state of SuccessRate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> SuccessRateOption { get; private set; }

        /// <summary>
        /// Gets or Sets SuccessRate
        /// </summary>
        [JsonPropertyName("success_rate")]
        public double? SuccessRate { get { return this.SuccessRateOption.Value; } set { this.SuccessRateOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SuccessRateResponse {\n");
            sb.Append("  Range: ").Append(Range).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  Failed: ").Append(Failed).Append("\n");
            sb.Append("  Pending: ").Append(Pending).Append("\n");
            sb.Append("  SuccessRate: ").Append(SuccessRate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SuccessRateResponse" />
    /// </summary>
    public class SuccessRateResponseJsonConverter : JsonConverter<SuccessRateResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="SuccessRateResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SuccessRateResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> range = default;
            Option<int?> successful = default;
            Option<int?> failed = default;
            Option<int?> pending = default;
            Option<double?> successRate = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "range":
                            range = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "successful":
                            successful = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "failed":
                            failed = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "pending":
                            pending = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "success_rate":
                            successRate = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (range.IsSet && range.Value == null)
                throw new ArgumentNullException(nameof(range), "Property is not nullable for class SuccessRateResponse.");

            if (successful.IsSet && successful.Value == null)
                throw new ArgumentNullException(nameof(successful), "Property is not nullable for class SuccessRateResponse.");

            if (failed.IsSet && failed.Value == null)
                throw new ArgumentNullException(nameof(failed), "Property is not nullable for class SuccessRateResponse.");

            if (pending.IsSet && pending.Value == null)
                throw new ArgumentNullException(nameof(pending), "Property is not nullable for class SuccessRateResponse.");

            if (successRate.IsSet && successRate.Value == null)
                throw new ArgumentNullException(nameof(successRate), "Property is not nullable for class SuccessRateResponse.");

            return new SuccessRateResponse(range, successful, failed, pending, successRate);
        }

        /// <summary>
        /// Serializes a <see cref="SuccessRateResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="successRateResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SuccessRateResponse successRateResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, successRateResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SuccessRateResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="successRateResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SuccessRateResponse successRateResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (successRateResponse.RangeOption.IsSet && successRateResponse.Range == null)
                throw new ArgumentNullException(nameof(successRateResponse.Range), "Property is required for class SuccessRateResponse.");

            if (successRateResponse.RangeOption.IsSet)
                writer.WriteString("range", successRateResponse.Range);

            if (successRateResponse.SuccessfulOption.IsSet)
                writer.WriteNumber("successful", successRateResponse.SuccessfulOption.Value!.Value);

            if (successRateResponse.FailedOption.IsSet)
                writer.WriteNumber("failed", successRateResponse.FailedOption.Value!.Value);

            if (successRateResponse.PendingOption.IsSet)
                writer.WriteNumber("pending", successRateResponse.PendingOption.Value!.Value);

            if (successRateResponse.SuccessRateOption.IsSet)
                writer.WriteNumber("success_rate", successRateResponse.SuccessRateOption.Value!.Value);
        }
    }
}
