// <auto-generated>
/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using hooksniff.Client;

namespace hooksniff.Model
{
    /// <summary>
    /// TwoFactorRequiredResponse
    /// </summary>
    public partial class TwoFactorRequiredResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TwoFactorRequiredResponse" /> class.
        /// </summary>
        /// <param name="requires2fa">requires2fa</param>
        /// <param name="tempToken">tempToken</param>
        /// <param name="message">message</param>
        [JsonConstructor]
        public TwoFactorRequiredResponse(Option<bool?> requires2fa = default, Option<string?> tempToken = default, Option<string?> message = default)
        {
            Requires2faOption = requires2fa;
            TempTokenOption = tempToken;
            MessageOption = message;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Requires2fa
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> Requires2faOption { get; private set; }

        /// <summary>
        /// Gets or Sets Requires2fa
        /// </summary>
        /* <example>true</example> */
        [JsonPropertyName("requires_2fa")]
        public bool? Requires2fa { get { return this.Requires2faOption.Value; } set { this.Requires2faOption = new(value); } }

        /// <summary>
        /// Used to track the state of TempToken
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TempTokenOption { get; private set; }

        /// <summary>
        /// Gets or Sets TempToken
        /// </summary>
        [JsonPropertyName("temp_token")]
        public string? TempToken { get { return this.TempTokenOption.Value; } set { this.TempTokenOption = new(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption.Value; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TwoFactorRequiredResponse {\n");
            sb.Append("  Requires2fa: ").Append(Requires2fa).Append("\n");
            sb.Append("  TempToken: ").Append(TempToken).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TwoFactorRequiredResponse" />
    /// </summary>
    public class TwoFactorRequiredResponseJsonConverter : JsonConverter<TwoFactorRequiredResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="TwoFactorRequiredResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TwoFactorRequiredResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> requires2fa = default;
            Option<string?> tempToken = default;
            Option<string?> message = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "requires_2fa":
                            requires2fa = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "temp_token":
                            tempToken = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (requires2fa.IsSet && requires2fa.Value == null)
                throw new ArgumentNullException(nameof(requires2fa), "Property is not nullable for class TwoFactorRequiredResponse.");

            if (tempToken.IsSet && tempToken.Value == null)
                throw new ArgumentNullException(nameof(tempToken), "Property is not nullable for class TwoFactorRequiredResponse.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class TwoFactorRequiredResponse.");

            return new TwoFactorRequiredResponse(requires2fa, tempToken, message);
        }

        /// <summary>
        /// Serializes a <see cref="TwoFactorRequiredResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="twoFactorRequiredResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TwoFactorRequiredResponse twoFactorRequiredResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, twoFactorRequiredResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TwoFactorRequiredResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="twoFactorRequiredResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TwoFactorRequiredResponse twoFactorRequiredResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (twoFactorRequiredResponse.TempTokenOption.IsSet && twoFactorRequiredResponse.TempToken == null)
                throw new ArgumentNullException(nameof(twoFactorRequiredResponse.TempToken), "Property is required for class TwoFactorRequiredResponse.");

            if (twoFactorRequiredResponse.MessageOption.IsSet && twoFactorRequiredResponse.Message == null)
                throw new ArgumentNullException(nameof(twoFactorRequiredResponse.Message), "Property is required for class TwoFactorRequiredResponse.");

            if (twoFactorRequiredResponse.Requires2faOption.IsSet)
                writer.WriteBoolean("requires_2fa", twoFactorRequiredResponse.Requires2faOption.Value!.Value);

            if (twoFactorRequiredResponse.TempTokenOption.IsSet)
                writer.WriteString("temp_token", twoFactorRequiredResponse.TempToken);

            if (twoFactorRequiredResponse.MessageOption.IsSet)
                writer.WriteString("message", twoFactorRequiredResponse.Message);
        }
    }
}
