ALTER TABLE customers ADD COLUMN IF NOT EXISTS is_active BOOL NOT NULL DEFAULT true;
        ALTER TABLE customers ADD COLUMN IF NOT EXISTS is_admin BOOL NOT NULL DEFAULT false;
        ALTER TABLE customers ADD COLUMN IF NOT EXISTS name TEXT;
