# coding: utf-8

"""
    HookSniff API

    Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@hooksniff.vercel.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EndpointHealth(BaseModel):
    """
    Endpoint health metrics and status
    """ # noqa: E501
    endpoint_id: UUID
    is_healthy: StrictBool
    failure_streak: Optional[StrictInt] = None
    avg_response_ms: Optional[StrictInt] = None
    last_failure_at: Optional[datetime] = None
    success_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Success rate as a fraction (0.0–1.0)")
    avg_latency_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average delivery latency in milliseconds")
    last_delivery_at: Optional[datetime] = None
    total_deliveries: Optional[StrictInt] = None
    failed_deliveries: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["endpoint_id", "is_healthy", "failure_streak", "avg_response_ms", "last_failure_at", "success_rate", "avg_latency_ms", "last_delivery_at", "total_deliveries", "failed_deliveries"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EndpointHealth from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EndpointHealth from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "endpoint_id": obj.get("endpoint_id"),
            "is_healthy": obj.get("is_healthy"),
            "failure_streak": obj.get("failure_streak"),
            "avg_response_ms": obj.get("avg_response_ms"),
            "last_failure_at": obj.get("last_failure_at"),
            "success_rate": obj.get("success_rate"),
            "avg_latency_ms": obj.get("avg_latency_ms"),
            "last_delivery_at": obj.get("last_delivery_at"),
            "total_deliveries": obj.get("total_deliveries"),
            "failed_deliveries": obj.get("failed_deliveries")
        })
        return _obj


