# coding: utf-8

"""
    HookSniff API

    Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@hooksniff.vercel.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Union
from hooksniff.models.system_status_components_inner import SystemStatusComponentsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SystemStatus(BaseModel):
    """
    SystemStatus
    """ # noqa: E501
    overall_status: StrictStr
    uptime_30d: Union[StrictFloat, StrictInt]
    components: List[SystemStatusComponentsInner]
    checked_at: StrictStr
    __properties: ClassVar[List[str]] = ["overall_status", "uptime_30d", "components", "checked_at"]

    @field_validator('overall_status')
    def overall_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['operational', 'degraded', 'down']):
            raise ValueError("must be one of enum values ('operational', 'degraded', 'down')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in components (list)
        _items = []
        if self.components:
            for _item_components in self.components:
                if _item_components:
                    _items.append(_item_components.to_dict())
            _dict['components'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "overall_status": obj.get("overall_status"),
            "uptime_30d": obj.get("uptime_30d"),
            "components": [SystemStatusComponentsInner.from_dict(_item) for _item in obj["components"]] if obj.get("components") is not None else None,
            "checked_at": obj.get("checked_at")
        })
        return _obj


