/**
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Admin alert rule with customer info
*/
export class AdminAlertRule {
    'id': string;
    'customerId'?: string;
    'customerEmail'?: string | null;
    'name': string;
    'condition': AdminAlertRule.ConditionEnum;
    'threshold': number;
    'channels': Array<AdminAlertRule.ChannelsEnum>;
    'isActive': boolean;
    'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "customerId",
            "baseName": "customer_id",
            "type": "string"
        },
        {
            "name": "customerEmail",
            "baseName": "customer_email",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "AdminAlertRule.ConditionEnum"
        },
        {
            "name": "threshold",
            "baseName": "threshold",
            "type": "number"
        },
        {
            "name": "channels",
            "baseName": "channels",
            "type": "Array<AdminAlertRule.ChannelsEnum>"
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return AdminAlertRule.attributeTypeMap;
    }
}

export namespace AdminAlertRule {
    export enum ConditionEnum {
        FailureRate = <any> 'failure_rate',
        Latency = <any> 'latency',
        ConsecutiveFailures = <any> 'consecutive_failures'
    }
    export enum ChannelsEnum {
        Slack = <any> 'slack',
        Email = <any> 'email',
        Webhook = <any> 'webhook'
    }
}
