/**
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AdminUsersIdGet200ResponseEndpointsInner } from './adminUsersIdGet200ResponseEndpointsInner';
import { AdminUsersIdGet200ResponseRecentDeliveriesInner } from './adminUsersIdGet200ResponseRecentDeliveriesInner';
import { AdminUsersIdGet200ResponseUsageStats } from './adminUsersIdGet200ResponseUsageStats';
import { UserSummary } from './userSummary';

export class AdminUsersIdGet200Response {
    'user'?: UserSummary;
    'endpoints'?: Array<AdminUsersIdGet200ResponseEndpointsInner>;
    'recentDeliveries'?: Array<AdminUsersIdGet200ResponseRecentDeliveriesInner>;
    'usageStats'?: AdminUsersIdGet200ResponseUsageStats;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "UserSummary"
        },
        {
            "name": "endpoints",
            "baseName": "endpoints",
            "type": "Array<AdminUsersIdGet200ResponseEndpointsInner>"
        },
        {
            "name": "recentDeliveries",
            "baseName": "recent_deliveries",
            "type": "Array<AdminUsersIdGet200ResponseRecentDeliveriesInner>"
        },
        {
            "name": "usageStats",
            "baseName": "usage_stats",
            "type": "AdminUsersIdGet200ResponseUsageStats"
        }    ];

    static getAttributeTypeMap() {
        return AdminUsersIdGet200Response.attributeTypeMap;
    }
}

