/**
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* System-level status for admin dashboard
*/
export class AdminSystemStatus {
    'version': string;
    'uptimeSeconds': number;
    'dbStatus': AdminSystemStatus.DbStatusEnum;
    'redisStatus': AdminSystemStatus.RedisStatusEnum;
    /**
    * Number of pending jobs in the delivery queue
    */
    'queueDepth': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "uptimeSeconds",
            "baseName": "uptime_seconds",
            "type": "number"
        },
        {
            "name": "dbStatus",
            "baseName": "db_status",
            "type": "AdminSystemStatus.DbStatusEnum"
        },
        {
            "name": "redisStatus",
            "baseName": "redis_status",
            "type": "AdminSystemStatus.RedisStatusEnum"
        },
        {
            "name": "queueDepth",
            "baseName": "queue_depth",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AdminSystemStatus.attributeTypeMap;
    }
}

export namespace AdminSystemStatus {
    export enum DbStatusEnum {
        Healthy = <any> 'healthy',
        Degraded = <any> 'degraded',
        Down = <any> 'down'
    }
    export enum RedisStatusEnum {
        Healthy = <any> 'healthy',
        Degraded = <any> 'degraded',
        Down = <any> 'down'
    }
}
