/**
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AnalyticsTrendPoint } from './analyticsTrendPoint';

/**
* Delivery trend data over a time period
*/
export class AnalyticsTrendResponse {
    /**
    * Array of trend data points
    */
    'data': Array<AnalyticsTrendPoint>;
    /**
    * Time range of the data
    */
    'period': AnalyticsTrendResponse.PeriodEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<AnalyticsTrendPoint>"
        },
        {
            "name": "period",
            "baseName": "period",
            "type": "AnalyticsTrendResponse.PeriodEnum"
        }    ];

    static getAttributeTypeMap() {
        return AnalyticsTrendResponse.attributeTypeMap;
    }
}

export namespace AnalyticsTrendResponse {
    export enum PeriodEnum {
        _24h = <any> '24h',
        _7d = <any> '7d',
        _30d = <any> '30d'
    }
}
