/**
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A single audit log record
*/
export class AuditLogEntry {
    'id': string;
    /**
    * Who performed the action (user id or email)
    */
    'actor': string;
    /**
    * The action taken (e.g. endpoint.create, team.invite)
    */
    'action': string;
    /**
    * Type of resource affected (endpoint, team, api_key, etc.)
    */
    'resourceType': string;
    /**
    * ID of the affected resource
    */
    'resourceId': string;
    'timestamp': Date;
    /**
    * Additional context (old_value, new_value, ip, etc.)
    */
    'metadata'?: object | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "actor",
            "baseName": "actor",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "string"
        },
        {
            "name": "resourceType",
            "baseName": "resource_type",
            "type": "string"
        },
        {
            "name": "resourceId",
            "baseName": "resource_id",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return AuditLogEntry.attributeTypeMap;
    }
}

