/**
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BatchResponseErrorsInner } from './batchResponseErrorsInner';
import { Delivery } from './delivery';

export class BatchResponse {
    'deliveries': Array<Delivery>;
    'errors': Array<BatchResponseErrorsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deliveries",
            "baseName": "deliveries",
            "type": "Array<Delivery>"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<BatchResponseErrorsInner>"
        }    ];

    static getAttributeTypeMap() {
        return BatchResponse.attributeTypeMap;
    }
}

