/**
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Visual customization for the embed
*/
export class EmbedConfigTheme {
    'primaryColor'?: string;
    'backgroundColor'?: string;
    'fontFamily'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "primaryColor",
            "baseName": "primary_color",
            "type": "string"
        },
        {
            "name": "backgroundColor",
            "baseName": "background_color",
            "type": "string"
        },
        {
            "name": "fontFamily",
            "baseName": "font_family",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EmbedConfigTheme.attributeTypeMap;
    }
}

