/**
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InviteRequest {
    'email': string;
    'role'?: InviteRequest.RoleEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "InviteRequest.RoleEnum"
        }    ];

    static getAttributeTypeMap() {
        return InviteRequest.attributeTypeMap;
    }
}

export namespace InviteRequest {
    export enum RoleEnum {
        Admin = <any> 'admin',
        Member = <any> 'member',
        Viewer = <any> 'viewer'
    }
}
