/**
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class LatencyTrendResponseBucketsInner {
    'timestamp'?: string;
    'avgMs'?: number;
    'p95Ms'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string"
        },
        {
            "name": "avgMs",
            "baseName": "avg_ms",
            "type": "number"
        },
        {
            "name": "p95Ms",
            "baseName": "p95_ms",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return LatencyTrendResponseBucketsInner.attributeTypeMap;
    }
}

