/**
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* List of static outbound IP addresses for firewall whitelisting
*/
export class OutboundIPsResponse {
    /**
    * IPv4 and IPv6 addresses used for outbound requests
    */
    'ips': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ips",
            "baseName": "ips",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return OutboundIPsResponse.attributeTypeMap;
    }
}

