/**
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Result of a simulated webhook delivery
*/
export class SimulatorResponse {
    'deliveryId': string;
    'status': SimulatorResponse.StatusEnum;
    /**
    * Response time from the endpoint
    */
    'latencyMs': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deliveryId",
            "baseName": "delivery_id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SimulatorResponse.StatusEnum"
        },
        {
            "name": "latencyMs",
            "baseName": "latency_ms",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SimulatorResponse.attributeTypeMap;
    }
}

export namespace SimulatorResponse {
    export enum StatusEnum {
        Delivered = <any> 'delivered',
        Failed = <any> 'failed',
        Pending = <any> 'pending'
    }
}
