/**
 * HookSniff API
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SuccessRateResponse {
    'range': string;
    'successful': number;
    'failed': number;
    'pending': number;
    'successRate': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "range",
            "baseName": "range",
            "type": "string"
        },
        {
            "name": "successful",
            "baseName": "successful",
            "type": "number"
        },
        {
            "name": "failed",
            "baseName": "failed",
            "type": "number"
        },
        {
            "name": "pending",
            "baseName": "pending",
            "type": "number"
        },
        {
            "name": "successRate",
            "baseName": "success_rate",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SuccessRateResponse.attributeTypeMap;
    }
}

